### ISSUE TITLE
Error "Object parameter [...] binding not supported" with custom base types (DBeaver 7.2.4, PostgreSQL 13)

### ISSUE THREAD

**Issue by vicreal** [dbeaver/dbeaver#10353]
**Windows 10 + DBeaver 7.2.4 + PostgreSQL 13** (tunnels or proxies not used).
The bug is only in the case of using **[custom base types](https://www.postgresql.org/docs/13/sql-createtype.html#id-1.9.3.94.5.8)**. For example:
```
CREATE EXTENSION uint;  -- add unsigned int datatypes / https://github.com/petere/pguint
CREATE TABLE test(id uint4);
INSERT INTO test VALUES(5);
```
If you then try to add or change any value in the "id" column via the DBeaver interface, an error occurs: "_Object parameter [...] binding not supported_" ([pguint](https://github.com/petere/pguint) is a popular extension, written by _PostgreSQL Core Team member_).
**Version 7.2.1 is working correctly with uint types**.

In the process of fixing this bug, please also fix the following **4 artifacts with user base types**:
...
(at the @LonwoLonwo request, this 4 artifacts were issued with a separate [ticket #10818](https://github.com/dbeaver/dbeaver/issues/10818) as feature request)

**Comment by voltaek** [comment]
Seeing the same issue on v7.2.5 on Windows with MS SQL Server when trying to update a column of type 'money', which as far as I'm aware is a standard SQL Server column type.

**Comment by sekullbe** [comment]
I also get the error on 7.3.0 with mysql 5.7, exporting a DB table that contains an enum column from one server to another (export to database table).

**Comment by Thomas-1985** [comment]
I have the same when trying to migrate a database (tables of it) to another (empty) using the "export data" wizard
The source table contains an enum

DBMS: MariaDB 10.5.4 (source and destination)

**Comment by LonwoLonwo** [comment]
Hello @vicreal 
Can you please create another ticket for "fix the following 4 artifacts with user base types." as feature request. 
I will not be able to resolve these issues with this ticket.

**Comment by vicreal** [comment]
**@LonwoLonwo**
Сreated a new ticket for artifacts with user base types [#10818](https://github.com/dbeaver/dbeaver/issues/10818) as feature request

**Comment by LonwoLonwo** [comment]
Can't reproduce in 7.3.1 with pguint data types. An error does not occur when inserting data into a table via UI.
@vicreal please test [new versions of DBeaver](https://dbeaver.io/)

**Comment by vicreal** [comment]
@LonwoLonwo
Сhecked version 7.2.5 - the error does not occur. In 7.3.1 version the error is also not occur.
So, the **bug with uint types in PostgreSQL** was fixed already **since 7.2.5** version (error occurred in 7.2.2, 7.2.3 and 7.2.4 versions).

**Comment by LonwoLonwo** [comment]
@vicreal thanks for answer!

**Comment by LonwoLonwo** [comment]
+ sqlserver "money" and "smallmoney" types editing via UI fixed
+ enum and set types data transfer error fixed

**Comment by LonwoLonwo** [comment]
sqlserver money datatransfer mapping type fixed

**Comment by kamilkiljan** [comment]
Problem still occurs for DBeaver 7.3.4 + PostgreSQL 11.5 + Linux MATE 1.16.2  when trying to delete row with column having custom data type or updating value in the column (also occurred for DBeaver 7.3.2 which I used previously).

**Comment by LonwoLonwo** [comment]
@kamilkiljan Can you provide example of custom type?

Probably, like workaround, after connecting to the database, you can go to the "public" schema and open the "Data Types" tab. Should help with caching custom data types.

**Comment by Thomas-1985** [comment]
For me it is working in 21.0.1 (Mac OS)

DBMS: MariaDB 10.5.4 (source and destination)

**Comment by MAH69IK** [comment]
Hi! I got some error on Linux with DBeaver 21.2.5 CE and ClickHouse with [IPv4](https://clickhouse.com/docs/en/sql-reference/data-types/domains/ipv4/) data types. When I try delete row I receive `Object parameter [<my_IP>] binding not supported`. Can you fix please?

**Comment by LonwoLonwo** [comment]
Hello @MAH69IK 

You can create a new ticket for this. Please add to the ticket table DDL and data samples for investigation.
