### ISSUE TITLE
Session Manager display Error While Connecting to a Oracle 9.2.0.8 with oJDBC driver 12.2.0.1

### ISSUE THREAD

**Issue by luiscarlosbolanhos** [dbeaver/dbeaver#10515]
SQL Error [904] [42000]: ORA-00904: "S"."SQL_CHILD_NUMBER": invalid identifier

  Error : 904, Position : 211, Sql = SELECT s.*, sq.SQL_FULLTEXT, io.*
FROM GV$SESSION s, gv$sql sq, gv$sess_io io
WHERE s.sql_address = sq.address(+)
 AND s.sql_hash_value = sq.hash_value(+) AND s.sid = io.sid(+) AND s.inst_id = io.inst_id(+) AND s.sql_child_number = sq.child_number (+) AND s.TYPE = 'USER' AND s.STATUS <> 'INACTIVE', OriginalSql = SELECT s.*, sq.SQL_FULLTEXT, io.*
FROM GV$SESSION s, gv$sql sq, gv$sess_io io
WHERE s.sql_address = sq.address(+)
 AND s.sql_hash_value = sq.hash_value(+) AND s.sid = io.sid(+) AND s.inst_id = io.inst_id(+) AND s.sql_child_number = sq.child_number (+) AND s.TYPE = 'USER' AND s.STATUS <> 'INACTIVE', Error Msg = ORA-00904: "S"."SQL_CHILD_NUMBER": invalid identifier

  ORA-00904: "S"."SQL_CHILD_NUMBER": invalid identifier

**Comment by LonwoLonwo** [comment]
@luiscarlosbolanhos Thank you for bug report. 
it looks like SQL_CHILD_NUMBER column only appeared in [11 Oracle](https://docs.oracle.com/cd/E18283_01/server.112/e17110/dynviews_1007.htm).
I will fixed it soon.

**Comment by LonwoLonwo** [comment]
@luiscarlosbolanhos Can you please check this statement
SELECT
	s.*,
	sq.SQL_TEXT,
	io.*
FROM
	GV$SESSION s,
	gv$sql sq,
	gv$sess_io io
WHERE
	s.sql_address = sq.address(+)
	AND s.sql_hash_value = sq.hash_value(+)
	AND s.sid = io.sid(+)
	AND s.inst_id = io.inst_id(+)

Unfortunately, we do not have test 9 Oracle database, so it will be very helpful if you check if this query is executed correctly in version 9.
Thanks!

**Comment by luiscarlosbolanhos** [comment]
> @luiscarlosbolanhos Thank you for bug report.
> it looks like SQL_CHILD_NUMBER column only appeared in [11 Oracle](https://docs.oracle.com/cd/E18283_01/server.112/e17110/dynviews_1007.htm).
> I will fixed it soon.

You are Right! Thanks a lot!

**Comment by luiscarlosbolanhos** [comment]
> SELECT
> s._, sq.SQL_TEXT, io._
> FROM
> GV$SESSION s,
> gv$sql sq,
> gv$sess_io io
> WHERE
> s.sql_address = sq.address(+)
> AND s.sql_hash_value = sq.hash_value(+)
> AND s.sid = io.sid(+)
> AND s.inst_id = io.inst_id(+)

Connected to:
Oracle9i Release 9.2.0.8.0 - 64bit Production
JServer Release 9.2.0.8.0 - Production

SQL> SELECT
s.,
sq.SQL_TEXT,
io.
FROM
GV$SESSION s,
gv$sql sq,
gv$sess_io io
WHERE
s.sql_address = sq.address(+)
AND s.sql_hash_value = sq.hash_value(+)
AND s.sid = io.sid(+)
AND s.inst_id = io.inst_id(+)  2    3    4    5    6    7    8    9   10   11   12   13  
 14  /
s.,
  *
ERROR at line 2:
ORA-01747: invalid user.table.column, table.column, or column specification

s., -- does not exists

**Comment by luiscarlosbolanhos** [comment]
SELECT
s.*,
sq.SQL_TEXT,
io.*
FROM
GV$SESSION s,
gv$sql sq,
gv$sess_io io
WHERE
s.sql_address = sq.address(+)
AND s.sql_hash_value = sq.hash_value(+)
AND s.sid = io.sid(+)
AND s.inst_id = io.inst_id(+)

The Code above works just fine on Oracle 9... please compare it with yours, and thanks a lot!

**Comment by luiscarlosbolanhos** [comment]
Please, to enable see and \* type: \\*

**Comment by LonwoLonwo** [comment]
@luiscarlosbolanhos oh, sorry, I completely forgot to escape characters, thanks! 
and for checking.

**Comment by LonwoLonwo** [comment]
Fixed in 7.3.1

**Comment by luiscarlosbolanhos** [comment]
> Fixed in 7.3.1

Thank you very much, I was confused with the 7.3.0 release note:

Oracle:
PL/SQL parser was significantly improved
View DDL read was fixed
**Session manager now supports Oracle 9 and 8**

I test the Session manager and the error still persist, Now I know why! It will be fixed in Fixed in 7.3.1! Great work Anastasiya! Best reagards and Wishes!

**Comment by LonwoLonwo** [comment]
@luiscarlosbolanhos Thanks so much for noticing! We will fix it soon.

**Comment by luiscarlosbolanhos** [comment]
> @luiscarlosbolanhos Thanks so much for noticing! We will fix it soon.

You are really Welcome! Regards.

**Comment by luiscarlosbolanhos** [comment]
I just install the EA version 7.3.0, The session manager works just great on 9.2.0.8 Oracle Database, thanks a lot! great work!

**Comment by LonwoLonwo** [comment]
@luiscarlosbolanhos Thanks for testing so much!
Enjoy working with DBeaver.
