### ISSUE TITLE
Update Homebrew Install Command

### ISSUE THREAD

**Issue by Smolations** [dbeaver/dbeaver#10577]
**Is your feature request related to a problem? Please describe.**
This is _very_ minor, but the instructions for mac on the download page include the command `brew cask install dbeaver-community`. While this command works, the current version of homebrew calls out:
> Warning: Calling brew cask install is deprecated! Use brew install [--cask] instead.

And just an aside, it would be nice if it is called out that java is required near that command instead of homebrew telling me i need it after a successful install or searching for the info somewhere on the page.

**Describe the solution you'd like**
_Option 1 (sufficient):_ `(brew install --cask dbeaver-community)`

**Describe alternatives you've considered**
_Option 2 (more info):_ ``(`brew install --cask dbeaver-community`; will provide install command for required java) ``

**Comment by serge-rider** [comment]
Thanks for bringing this up 👍 
Done.

**Comment by serge-rider** [comment]
BTW we include JDK in DMG installer since 7.3.1.

**Comment by kseniiaguzeeva** [comment]
New command is here https://dbeaver.io/download/

**Comment by ronlut** [comment]
@serge-rider The command is still wrong I think...
It should be: `brew install --cask dbeaver-community`
Currently it is: `brew install –cask dbeaver-community` (incorrect one dash)

**Comment by serge-rider** [comment]
@ronlut Uhh, that's a shame. 
Perhaps I should become a brew user and test it better 😞 
Fixed

**Comment by ronlut** [comment]
@serge-rider ;)
Cool!

**Comment by william-teamworx** [comment]
Hi, great project! But, I am here to report the Homebrew instructions on the download page still has just one dash instead of two. So, like @ronlut mentioned, it should be:
`brew install --cask dbeaver-community`

Also, on the newer Mac Big Sur, I didn't get a warning when I installed DBeaver without the "--cask" option. I think the OP might be on an older Mac, so their experience might still be valid too.

**Comment by kseniiaguzeeva** [comment]
New ticket https://github.com/dbeaver/dbeaver/issues/10919 is opened for the issue from the comment.
