### ISSUE TITLE
Autocompletion is not Proposing Table Names after "FROM"

### ISSUE THREAD

**Issue by GertL** [dbeaver/dbeaver#12330]
DBeaver Version: 21.0.2.202104042040
Database: SyBase IQ
Driver: jConnect - http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc01776.1602/doc/html/san1357754912881.html

In DBeaver prior versions, the SQL editor provided also autocomplete for Table Names, however in the latest, it has stopped proposing table-names as I type.

For example, if I type select * from , I want the very next letter I type to receive auto-completion proposals of table names that contain what I type after from , but it isn't.

Global "SQL Completion" settings attached.
![74144705-d5260a00-4bc2-11ea-89d2-c9ed3d091cca](https://user-images.githubusercontent.com/11056746/116863928-b1a80e80-ac0f-11eb-972b-33f4e227a0c2.png)

Please advise.

**Comment by kseniiaguzeeva** [comment]
Unfortunately, I cannot reproduce it. Please send a video where auto-completion doesn't work or a full query with table name example.

**Comment by GertL** [comment]
SELECT * 
FROM DW.Customer

It only works when I write the table name first. If I write the schema.table_name, it fails to auto-complete or offer a proposal

**Comment by mkgrgis** [comment]
PostGIS 3.0, Postgres 13
No autocompletion for schema names with spaces. Example
![изображение](https://user-images.githubusercontent.com/41448637/117534165-fa3d3e80-aff8-11eb-9415-2e5cfc2c2be5.png)
My SQL Completion options is the same with SQL completion options of @GertL.

**Comment by LonwoLonwo** [comment]
Hello @GertL 
We had problems with auto-completion in previous versions, but we fixed some of these problems.
Can you test latest version of DBeaver please?
https://dbeaver.io/
or better early access version of 21.0.5 https://dbeaver.io/files/ea/

**Comment by LonwoLonwo** [comment]
Hello @mkgrgis 
Autocomplete for schema name with space inside - is another issue. Please, create another ticket for this case.

**Comment by mkgrgis** [comment]
Thanks, @LonwoLonwo! I have created a new ticket.

**Comment by GertL** [comment]
But still, the issue for me is not resolved. None of the suggestions here worked.

**Comment by LonwoLonwo** [comment]
Auto-completion in SQL Editor depends on many conditions. Could you please be more specific? Do you use SQL Editor with default schema/database? When is the unwanted behavior observed?
Screens or video will be also very helpful.

**Comment by GertL** [comment]
Hi! 

The initial ticket has my settings for SQL editor. 

DBeaver Version: 21.0.2.202104042040
Database: SyBase IQ
Driver: jConnect 

And it is always this way.

**Comment by kseniiaguzeeva** [comment]
Could you please try the latest release? A lot of autocompletion bugs were fixed there https://dbeaver.io/.

If the issue still persists, could you please provide me with following details:
- Is default or non-default schema selected?
- A video with the bug.

**Comment by mkgrgis** [comment]
21.1.0 : no problems with schema names with spaces in Postgres.
Waiting for @GertL ...

**Comment by GertL** [comment]
Issue resolved with version 21.1.0

Thank you all!
