### ISSUE TITLE
oracle view table indexes report  an error: ORA-01417

### ISSUE THREAD

**Issue by oicq1699** [dbeaver/dbeaver#13025]
#### System information: 
- Operating system (distribution) and version : windows 10
- DBeaver version : 21.1.1
- Additional extensions

#### Connection specification:
- Database name and version :oracle 11gR2
- Driver name:ojdbc8
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : no

#### Describe the problem you're observing:
An error is reported when the table indexesis viewed. When I tried the earlier version (21.0.5), everything worked fine
#### Steps to reproduce, if exist:
Open an Oracle connection and select a table, right-click on the menu and select **view table**,Select the **indexes** item in the right panel.
#### Include any warning/errors/backtraces from the logs
ORA-01417: a table may be outer joined to at most one other table

SQL Error [1417] [72000]: ORA-01417: a table may be outer joined to at most one other table

  Error : 1417, Position : 397, Sql = SELECT  i.OWNER,i.INDEX_NAME,i.INDEX_TYPE,i.TABLE_OWNER,i.TABLE_NAME,i.UNIQUENESS,i.TABLESPACE_NAME,i.STATUS,i.NUM_ROWS,i.SAMPLE_SIZE,
ic.COLUMN_NAME,ic.COLUMN_POSITION,ic.COLUMN_LENGTH,ic.DESCEND,iex.COLUMN_EXPRESSION
FROM ALL_INDEXES i
, ALL_IND_COLUMNS ic, ALL_IND_EXPRESSIONS iex WHERE ic.INDEX_OWNER=i.OWNER AND ic.INDEX_NAME=i.INDEX_NAME 
AND iex.INDEX_OWNER(+)=i.OWNER AND iex.INDEX_NAME(+)=i.INDEX_NAME AND iex.COLUMN_POSITION(+)=ic.COLUMN_POSITION
AND i.TABLE_OWNER=:1  AND i.TABLE_NAME=:2 
ORDER BY i.INDEX_NAME,ic.COLUMN_POSITION, OriginalSql = SELECT  i.OWNER,i.INDEX_NAME,i.INDEX_TYPE,i.TABLE_OWNER,i.TABLE_NAME,i.UNIQUENESS,i.TABLESPACE_NAME,i.STATUS,i.NUM_ROWS,i.SAMPLE_SIZE,
ic.COLUMN_NAME,ic.COLUMN_POSITION,ic.COLUMN_LENGTH,ic.DESCEND,iex.COLUMN_EXPRESSION
FROM ALL_INDEXES i
, ALL_IND_COLUMNS ic, ALL_IND_EXPRESSIONS iex WHERE ic.INDEX_OWNER=i.OWNER AND ic.INDEX_NAME=i.INDEX_NAME 
AND iex.INDEX_OWNER(+)=i.OWNER AND iex.INDEX_NAME(+)=i.INDEX_NAME AND iex.COLUMN_POSITION(+)=ic.COLUMN_POSITION
AND i.TABLE_OWNER=? AND i.TABLE_NAME=?
ORDER BY i.INDEX_NAME,ic.COLUMN_POSITION, Error Msg = ORA-01417: a table may be outer joined to at most one other table

  ORA-01417: a table may be outer joined to at most one other table

**Comment by michaelbv** [comment]
Same as above essentially. 

**System information:**
Operating system (distribution) and version : ubuntu 20.04
DBeaver version : 21.1.1.202106210824
Additional extensions

**Connection specification:**
Database name and version :oracle 11gR2
Driver name: ojdbc8 release 12.2.0.1
Do you use tunnels or proxies (SSH, SOCKS, etc)? : SSH

**Describe the problem you're observing:**
The tables node shows some but not all (2 out of 100s in my case) tables. 
Sometimes an error (see below for log) is reported when the tables node is opened. 

**Steps to reproduce, if exist:**
Open an Oracle connection, right-click select the Tables node in the object tree and choose View Tables.

**Include any warning/errors/backtraces from the logs**
ORA-01417: a table may be outer joined to at most one other table

SQL Error [1417] [72000]: ORA-01417: a table may be outer joined to at most one other table

!STACK 0
Error : 1417, Position : 397, Sql = SELECT  i.OWNER,i.INDEX_NAME,i.INDEX_TYPE,i.TABLE_OWNER,i.TABLE_NAME,i.UNIQUENESS,i.TABLESPACE_NAME,i.STATUS,i.NUM_ROWS,i.SAMPLE_SIZE,
ic.COLUMN_NAME,ic.COLUMN_POSITION,ic.COLUMN_LENGTH,ic.DESCEND,iex.COLUMN_EXPRESSION
FROM ALL_INDEXES i
, ALL_IND_COLUMNS ic, ALL_IND_EXPRESSIONS iex WHERE ic.INDEX_OWNER=i.OWNER AND ic.INDEX_NAME=i.INDEX_NAME 
AND iex.INDEX_OWNER(+)=i.OWNER AND iex.INDEX_NAME(+)=i.INDEX_NAME AND iex.COLUMN_POSITION(+)=ic.COLUMN_POSITION
AND i.OWNER=:1 
ORDER BY i.INDEX_NAME,ic.COLUMN_POSITION, OriginalSql = SELECT  i.OWNER,i.INDEX_NAME,i.INDEX_TYPE,i.TABLE_OWNER,i.TABLE_NAME,i.UNIQUENESS,i.TABLESPACE_NAME,i.STATUS,i.NUM_ROWS,i.SAMPLE_SIZE,
ic.COLUMN_NAME,ic.COLUMN_POSITION,ic.COLUMN_LENGTH,ic.DESCEND,iex.COLUMN_EXPRESSION
FROM ALL_INDEXES i
, ALL_IND_COLUMNS ic, ALL_IND_EXPRESSIONS iex WHERE ic.INDEX_OWNER=i.OWNER AND ic.INDEX_NAME=i.INDEX_NAME 
AND iex.INDEX_OWNER(+)=i.OWNER AND iex.INDEX_NAME(+)=i.INDEX_NAME AND iex.COLUMN_POSITION(+)=ic.COLUMN_POSITION
AND i.OWNER=?
ORDER BY i.INDEX_NAME,ic.COLUMN_POSITION, Error Msg = ORA-01417: a table may be outer joined to at most one other table

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:498)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:446)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1054)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:623)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:252)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:612)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:226)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:59)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:747)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:904)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1082)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3780)
	at oracle.jdbc.driver.T4CPreparedStatement.executeInternal(T4CPreparedStatement.java:1343)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3887)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1079)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.loadObjects(JDBCCompositeCache.java:291)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.getObjects(JDBCCompositeCache.java:120)
	at org.jkiss.dbeaver.ext.oracle.model.OracleSchema.cacheStructure(OracleSchema.java:411)
	at org.jkiss.dbeaver.erd.model.ERDUtils.lambda$0(ERDUtils.java:141)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.erd.model.ERDUtils.collectDatabaseTables(ERDUtils.java:139)
	at org.jkiss.dbeaver.erd.ui.editor.ERDEditorEmbedded.loadFromDatabase(ERDEditorEmbedded.java:210)
	at org.jkiss.dbeaver.erd.ui.editor.ERDEditorEmbedded.access$1(ERDEditorEmbedded.java:193)
	at org.jkiss.dbeaver.erd.ui.editor.ERDEditorEmbedded$1.evaluate(ERDEditorEmbedded.java:168)
	at org.jkiss.dbeaver.erd.ui.editor.ERDEditorEmbedded$1.evaluate(ERDEditorEmbedded.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by michaelbv** [comment]
Same behaviour with 21.0.5.202105160657

**Comment by amoradell** [comment]
Error is with Oracle < 12c

It has been fixed : [https://docs.oracle.com/database/121/NEWFT/chapter12101.htm#NEWFT138](url)

Transforming Oracle native joins with ansi joins is ok in 11g

```
SELECT
	i.OWNER,
	i.INDEX_NAME,
	i.INDEX_TYPE,
	i.TABLE_OWNER,
	i.TABLE_NAME,
	i.UNIQUENESS,
	i.TABLESPACE_NAME,
	i.STATUS,
	i.NUM_ROWS,
	i.SAMPLE_SIZE,
	ic.COLUMN_NAME,
	ic.COLUMN_POSITION,
	ic.COLUMN_LENGTH,
	ic.DESCEND,
	iex.COLUMN_EXPRESSION
FROM
	ALL_INDEXES i
JOIN ALL_IND_COLUMNS ic ON
	i.owner = ic.index_owner
	AND i.index_name = ic.index_name
LEFT JOIN ALL_IND_EXPRESSIONS iex ON
	iex.index_owner = i.owner
	AND iex.INDEX_NAME = i.INDEX_NAME
	AND iex.COLUMN_POSITION = ic.COLUMN_POSITION
WHERE
	i.TABLE_OWNER = ?
	AND i.TABLE_NAME =?
ORDER BY
	i.INDEX_NAME,
	ic.COLUMN_POSITION
```

**Comment by uslss** [comment]
thanks for the report

**Comment by uslss** [comment]
the fix can be checked in [EA version](https://dbeaver.io/files/ea/)

**Comment by ugurbor** [comment]
I still have the issue on the EA Version 21.1.2.202107060947 (Linux DEB)

**Comment by uslss** [comment]
@ugurbor cannot reproduce it against 11g. which oracle version do you use?

**Comment by ugurbor** [comment]
From the `SELECT * FROM v$version`
`Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production`

These are the libraries from the connection properties. Don't really know if it matters: https://i.gyazo.com/fc1f53ed13c31db9c9c63257c39712cb.png

**Comment by michaelbv** [comment]
Same here when opening the Indexes node .
flyway 21.1.2.202107060947

**Comment by skotlex** [comment]
Me too. 
`Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production`
DBeaver version `21.1.2.202107060947`

**Comment by yexinfo** [comment]
Me too.
Oracle version:
Oracle Database 10g Enterprise Edition Release 10.2.0.1.0 - Prod
AND
Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit Production
All the same problem when opening the Indexes and DDL node.
DBeaver version: 21.1.2.202107060947

**Comment by uslss** [comment]
seems something going wrong with previous EA. Should be fixed in current EA version (Version 21.1.3.202107081153)

**Comment by yexinfo** [comment]
> seems something going wrong with previous EA. Should be fixed in current EA version (Version 21.1.3.202107081153)

I tested it and found it to be fixed. I'm not reporting any more bugs here, thanks!

**Comment by ugurbor** [comment]
I can confirm Version 21.1.3.202107081153 fixes the issue for me as well. Thanks.

**Comment by amoradell** [comment]
It's ok for me in Oracle Database 11g Release 11.2.0.1.0 - 64bit Production. Thanks.
