### ISSUE TITLE
Scheduler/jobs/Run Log is empty (oracle)

### ISSUE THREAD

**Issue by majkyyx** [dbeaver/dbeaver#14528]
![image](https://user-images.githubusercontent.com/14957734/141277318-aa9a3db4-e93c-43af-8719-0d88302cbe84.png)

#### System information: 
- Operating system: OS: Ubuntu Budgie 20.04.3 LTS x86_64 (Kernel: 5.11.0-38-generic ) - but it's same bug on windows 10
- DBeaver version: 21.2.4.202111011413

#### Connection specification:
- Database name and version: oracle 19c EE (but same bug on other versions of oracle)
- Driver name: ojdbc7.jar 

#### Describe the problem you're observing:
Run Log for dbms_scheduler is empty for every job
#### Steps to reproduce, if exist:
```sql
begin    DBMS_SCHEDULER.CREATE_JOB (
            job_name => 'MY_JOB',
            job_type => 'PLSQL_BLOCK',
            job_action => 'BEGIN
						null;
                           END;',
            number_of_arguments => 0,
            start_date => TO_TIMESTAMP_TZ('2014-04-04 01:30:00.000000000 EUROPE/PRAGUE','YYYY-MM-DD HH24:MI:SS.FF TZR'),
            repeat_interval => 'Freq=DAILY;ByHour=5;ByMinute=45',
            end_date => NULL,
            enabled => FALSE,
            auto_drop => FALSE,
            comments => 'desc');
END;            

BEGIN DBMS_SCHEDULER.run_job('MY_JOB',false); END;

SELECT * FROM USER_SCHEDULER_JOB_RUN_DETAILS  WHERE job_name ='MY_JOB' --this IS NOT empty 
```
and than go to: Scheduler/jobs/MY_JOB/Run Log and ther will be label "no data" 
(on screenshot it's diferent job, but it's same result for all jobs)

**Comment by uslss** [comment]
![image](https://user-images.githubusercontent.com/31996417/142193131-9d05da77-a464-437d-b475-e406683ffe2c.png)
unfortunately, cannot reproduce it.
Could you check if there is something in the[ log](https://github.com/dbeaver/dbeaver/wiki/Log-files)?

**Comment by majkyyx** [comment]
Log is empty, without erros. 

Which version of oracle R U using ? 
pls run this:
```sql
SELECT * FROM v$version
```
I have access to manny version of oracle, i can recheck this on same version.

**Comment by majkyyx** [comment]
Yes, it's about oracle version, i tried oracle 11g and it's working (on 19 it's not working):

![image](https://user-images.githubusercontent.com/14957734/142199553-940e5152-92ba-4c5d-b5b9-241db3f41525.png)

**Comment by uslss** [comment]
thanks for the report and clarification

**Comment by majkyyx** [comment]
|STATE|VERSION OF ORACLE|LICENCE|
|-|-|-|
| OK | Oracle Database 18c Express Edition Release 18.0.0.0.0 - Production | XE |
| BUG | Oracle Database 11g Release 11.2.0.4.0 - 64bit Production | SE |
| OK | Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production | XE |
| BUG | Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production | EE |
|OK | Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production | EE (EXA DATA) |

So, it's not about version, but maybe about some configuration of database, i don't know. 

But if dbeaver run SQL query like this:

```sql
SELECT * FROM USER_SCHEDULER_JOB_RUN_DETAILS  WHERE job_name = :job_name
```
this SQL query will be works everywhere

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 22.0.1

Now DBeaver will search for the `DBA_SCHEDULER_JOB_RUN_DETAILS` view first and, if not found - will use the `USER_SCHEDULER_JOB_RUN_DETAILS `view for the Jobs run log reading.

**Comment by majkyyx** [comment]
thx a lot guys :-) :+1:

**Comment by uslss** [comment]
verified

**Comment by majkyyx** [comment]
Hello @LonwoLonwo a tried this FIX and a'm not sure, it's working. Look on this screen please. Version is 22.0.1+ and i still see label "No Data" . 

I think it's becase correct name of view is ```USER_SCHEDULER_JOB_RUN_DETAILS``` not ```SCHEDULER_JOB_RUN_DETAILS``` if i'm looking on your commit.

![image](https://user-images.githubusercontent.com/14957734/161062034-d0b6c0b2-5800-485f-984d-2a6e4a317621.png)

**Comment by LonwoLonwo** [comment]
You can check the request table name in the Query Manager: https://github.com/dbeaver/dbeaver/wiki/Query-Manager

**Comment by majkyyx** [comment]
I've tried this before, but nothing is written here if a click on tab "Run log". 

But i'm pretty sure about wrong name of view in commit. There is not ```USER_``` prefix, view SCHEDULER_JOB_RUN_DETAILS not exists on oracle.

**Comment by LonwoLonwo** [comment]
![2022-03-31 16_37_00-Properties for Query Manager](https://user-images.githubusercontent.com/45152336/161067997-4ff9e922-ef67-43c2-858d-4381329e61f9.png)

Maybe not all settings are checked?

We do not use just the SCHEDULER_JOB_RUN_DETAILS view name. 
The OracleUtils.getSysUserViewName() method will check first the DBA_SCHEDULER_JOB_RUN_DETAILS VIEW and if did not find it - then DBeaver uses USER_SCHEDULER_JOB_RUN_DETAILS view.

![2022-03-31 16_37_36-DBeaver Ultimate 22 0 2 - MY_JOB](https://user-images.githubusercontent.com/45152336/161068084-a03f7772-fa71-4c7f-b2bf-c2317859a9b6.png)

**Comment by majkyyx** [comment]
If't user_Scheduler_job_run_details, it's correct.

I checked everthing In query manager.

I have grants on DBA_ and USER_ too. It's look like no query runs on tab "Run Log"

![image](https://user-images.githubusercontent.com/14957734/161071348-541a4fb4-eaa9-408d-9fb0-d43942ba060a.png)

And refresh button on tab "Run Log" is disabled.

**Comment by majkyyx** [comment]
A check this behavior on PC of my wife with same version 22.0.1  but on windows. It's same. Nothing in query manager when i clicked on "Run Log" tab. If i click on tab "Properties" then i can see:
```
SELECT * FROM ALL_SCHEDULER_JOB_ARGS WHERE OWNER='VERSO2' AND JOB_NAME='LL_AQ_KONTROLA_JOB' ORDER BY ARGUMENT_POSITION
```
So query manager works.

**Comment by LonwoLonwo** [comment]
Ok. It's time for the strange suggestions. Does your database have SYS schema?

**Comment by majkyyx** [comment]
Yes it has, i thing every oracle have "SYS" schema.

**Comment by LonwoLonwo** [comment]
Can you find the DBA_SCHEDULER_JOB_RUN_DETAILS view in the list of SYS schemas? 
(You can write SELECT x.* FROM SYS.DBA_SCHEDULER_JOB_RUN_DETAILS x in the SQL Editor and use ctrl+click on the view name)

Also, the [error log](https://github.com/dbeaver/dbeaver/wiki/Log-files) is still empty?

**Comment by majkyyx** [comment]
OK, i can't find schema SYS in schema browser, also i can't click on on SYS.DBA_SCHEDULER_JOB_RUN_DETAILS in SQL editor (but i can select from SYS.DBA_SCHEDULER_JOB_RUN_DETAILS)



I found SYS schema in VIEW all_users. 

I also checked logs in path (~/.local/share/DBeaverData/workspace6/.metadata) 
 - .log
 - dbeaver-debug.log
 and log on interface. 

All are empty when i click on "run log" tab.

**Comment by LonwoLonwo** [comment]
Usually, the SYS schema is not in the list if the Connection view is custom and the setting "Show system objects" is not enabled.

![2022-03-31 17_49_51-](https://user-images.githubusercontent.com/45152336/161084505-e63b9327-16b5-49e2-97e6-24ae645fc652.png)

Can you please check this setting?

**Comment by majkyyx** [comment]
Nice! 
Ok, i had custom connection view. When i switched and reconnect to advanced view, "run log" start working too.

**Comment by LonwoLonwo** [comment]
Ok, Thanks for the investigation @majkyyx 

Unfortunately, I can't reproduce with the Custom view also. I will try again later.

![2022-03-31 17_58_58-DBeaver Ultimate 22 0 2 - RUN_LOAD_SALES](https://user-images.githubusercontent.com/45152336/161086428-90de84c6-0d73-4eb3-8082-e2c55cbfb248.png)

**Comment by majkyyx** [comment]
Helo @LonwoLonwo Anastasiya , can we continue in this issue? Do u have time for this? thx

**Comment by LonwoLonwo** [comment]
Hello @majkyyx 
I can't reproduce your issue.

Maybe you can add some grants for DBA_SCHEDULER_JOB_RUN_DETAILS and use DBA views as default with this Connection setting ? 

![2022-10-12 12_37_44-DBeaver Ultimate 22 2 2 - child_a](https://user-images.githubusercontent.com/45152336/195307966-70f727ed-cbab-44f5-8d73-58b833d21451.png)

**Comment by majkyyx** [comment]
![image](https://user-images.githubusercontent.com/14957734/195334001-19f19965-3cde-4938-a994-e2482adee37f.png)

It's not helping, i have rights to see DBA_SCHEDULER_JOB_RUN_DETAILS, in connection setting checked this option and "Run log" is still empty. But i thing it will be something about the grands of schema.

**Comment by majkyyx** [comment]
I'll try found same DB where "run log" is working and try to compare the grants. I'll let you know.

**Comment by majkyyx** [comment]
I found something. I found DB with two schemas, one working and one not working.

Schema "provoz" is working. 
Schema "verso2" is not working.

Same connection (it's copied), same DB,same SID/service_name, same version, everything)

Only one diferent what i found is in table "user_tab_privs" where is grant to DBMS_SHEDULER

![image](https://user-images.githubusercontent.com/14957734/195347111-499b569d-57a5-48a6-bbc2-d41cd7b7ba33.png)

![image](https://user-images.githubusercontent.com/14957734/195347591-e72b4e76-6485-449c-ab58-fe0ab853d2b3.png)



Other DB where is working is different, there is role grant 
![image](https://user-images.githubusercontent.com/14957734/195347780-b645add7-ca4b-4544-addf-0b7b8ea9216c.png)



It's a helpful for U ? :)

**Comment by LonwoLonwo** [comment]
Can you please check this tree tables for "verso2"? Does any of these tables has info inside?

```sql
SELECT x.* FROM SYS.DBA_SCHEDULER_JOB_RUN_DETAILS
SELECT x.* FROM SYS.ALL_SCHEDULER_JOB_RUN_DETAILS
SELECT x.* FROM SYS.USER_SCHEDULER_JOB_RUN_DETAILS
```

**Comment by majkyyx** [comment]
yeah, all of those select works and resuluts has data.

![image](https://user-images.githubusercontent.com/14957734/195516910-b2a65001-986f-47a2-a7a8-859063cfe5af.png)

**Comment by LonwoLonwo** [comment]
But "run log" just query "SELECT * FROM SCHEDULER_JOB_RUN_DETAILS" :(

Can you check your [query manager](https://github.com/dbeaver/dbeaver/wiki/Query-Manager) again then?

**Comment by majkyyx** [comment]
i cleaned query manager and just double click on the first job. (default tab is Run log, dbeaver remeber this tab from last opening)

there are 5 queries:

```sql
SELECT * FROM ALL_SCHEDULER_JOB_ARGS WHERE OWNER='VERSO2' AND JOB_NAME='ADM_CERP_JOB' ORDER BY ARGUMENT_POSITION
```
```sql
SELECT * FROM ALL_SCHEDULER_JOBS WHERE OWNER='VERSO2' ORDER BY JOB_NAME
```
```sql
SELECT  OBJECT_NAME, STATUS FROM ALL_OBJECTS WHERE OBJECT_TYPE='PACKAGE' AND OWNER='VERSO2'  ORDER BY OBJECT_NAME
```
```sql
SELECT  * FROM ALL_TYPES WHERE OWNER='VERSO2' ORDER BY TYPE_NAME
```
```sql
SELECT  O.*,
t.TABLE_TYPE_OWNER,t.TABLE_TYPE,t.TABLESPACE_NAME,t.PARTITIONED,t.IOT_TYPE,t.IOT_NAME,t.TEMPORARY,t.
SECONDARY,t.NESTED,t.NUM_ROWS
FROM ALL_OBJECTS O
, ALL_ALL_TABLES t WHERE t.OWNER(+) = O.OWNER AND t.TABLE_NAME(+) = o.OBJECT_NAME
AND O.OWNER='VERSO2' AND O.OBJECT_TYPE IN ('TABLE', 'VIEW', 'MATERIALIZED VIEW')
```

![image](https://user-images.githubusercontent.com/14957734/195523594-4f231063-ed8b-4250-99a1-9f6842591879.png)

**Comment by majkyyx** [comment]
I think is not about rights to select user_scheduler_job_run_details. It's about dbeaver just don't run this query somehow.

**Comment by majkyyx** [comment]
I can show you this online via google meet or something if you want :-)

**Comment by LonwoLonwo** [comment]
Ok. Step back.

https://github.com/dbeaver/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.ext.oracle.ui/src/org/jkiss/dbeaver/ext/oracle/ui/editors/SchedulerJobLogEditor.java#L112

You can see that DBeaver returns the SYS schema view as the log. Do you have the SYS schema in your schemas list?

**Comment by LonwoLonwo** [comment]
SYS schema is visible with the Advanced connection view.

**Comment by majkyyx** [comment]
OK, i switched to advanced in connection view and it's starts working. Schema sys is visible. 

![image](https://user-images.githubusercontent.com/14957734/195527438-5032fa7e-f7bb-43f8-ae9f-e3d5b9dbbaa7.png)

Before i switched to advanced, there was custom connection view with all checkboxes checked.

**Comment by LonwoLonwo** [comment]
Ok. So. The issue is - the "Run log" isn't available for non-advanced types of connection views.
Can you create a new ticket for this? With the link to this ticket.

**Comment by majkyyx** [comment]
I know! It's working only when SYS schema is visible in schema list. Because if i use the schema filtr, and sys schema is hidden, it stops working.

![image](https://user-images.githubusercontent.com/14957734/195528882-8d882fa9-97f4-4186-8e8e-f8cbb01ae5ef.png)

![image](https://user-images.githubusercontent.com/14957734/195529195-84f00ef7-ffaf-44ce-b49f-fff3f4c7f3db.png)

**Comment by majkyyx** [comment]
Thank you Anastasiya for this investigation.
I made new issue https://github.com/dbeaver/dbeaver/issues/17909

Have a nice day.

bye
