### ISSUE TITLE
After upgrade, the theming customization is reset and theme plugin is no longer available

### ISSUE THREAD

**Issue by VipSaran** [dbeaver/dbeaver#14927]
#### System information: 
- Operating system (distribution) and version
Edition	Windows 10 Enterprise N
Version	21H2
Installed on	‎19.‎06.‎2020.
OS build	19044.1348
Experience	Windows Feature Experience Pack 120.2212.3920.0
- DBeaver version: 21.3.1.202112130652 (community)
- Additional extensions
![image](https://user-images.githubusercontent.com/995948/146335851-fdac542d-4880-4c18-ba6a-a233b86424fd.png)

#### Describe the problem you're observing:
After last 2 upgrades (to 21.3.0 and to 21.3.1), the theming customization is reset and theme plugin (DevStyle) is no longer available.

#### Steps to reproduce, if exist:
1. install DevStyle
2. select it:
![image](https://user-images.githubusercontent.com/995948/146347624-0eb97c07-b891-413f-94f3-68931b36ef7c.png)
3. (restart DBeaver to apply etc.) 
4. upgrade DBeaver

Expected would be for upgrade to leave the Styling customizations as they were.

#### Include any warning/errors/backtraces from the logs
[metadata.zip](https://github.com/dbeaver/dbeaver/files/7726160/metadata.zip)

**Comment by rrousselot** [comment]
I have never, to my knowledge, used DevStyle but I do use Dark Mode and as OP has indicated this seems to have been broken.

**Comment by LeMapper** [comment]
Seems like there has been some trouble with paths, lately. I updated to DBeaver CE 21.3.0.202112091630 via Microsoft Store lately. I now can't create new connections to Oracle servers, because the path to WindowsApps\DbeaverCorp.DBeaverCE_...\plugins/org.eclipse.equinox.launcher contains a forward slash and cannot be found 😅
'AutoRegisterSchemeHandlersJob has encountered a problem'

**Comment by Matvey16** [comment]
@VipSaran Unfortunately this plugin is not included in our installation package, so it needs to be reinstalled after every DBeaver update. Adding it to the package has other issues, but we will return to this in the future

**Comment by VipSaran** [comment]
The problem is -- I use the plugin for a few years now and only with DBeaver v21+ the problems started, so some sort of regression occured (or an incompatible change was introduced) in that/later versions.

**Comment by Matvey16** [comment]
It may be connected with the fact that we updated the Eclipse version in 21.3.0. Looks like it should be fixed

**Comment by paul-eeoc** [comment]
Whenever I upgrade DBeaver, (now on v. 22.0.0), I always had to re-install the office plugin.
DBeaver Office integration - https://dbeaver.io/update/office/latest/

**Comment by davidhooey** [comment]
I have the same issue with the VRapper (VIM plugin). Every upgrade forces the reinstall of the plugin.

**Comment by uslss** [comment]
#5317

**Comment by alecyu** [comment]
it still happening with latest version at this point, all installed plugins are have to re-install and customize every plugins again after DBeaver upgrade

**Comment by dossy** [comment]
> @VipSaran Unfortunately this plugin is not included in our installation package, so it needs to be reinstalled after every DBeaver update. Adding it to the package has other issues, but we will return to this in the future

User-installed customizations should not be stored with the DBeaver application files, but in the user's home directory, so that application updates do not interfere with user customizations.

This is a major annoyance of using DBeaver, and discourages me from updating it.

**Comment by alecyu** [comment]
It is very annoying on every installed plugins have to be re-installed again, again and again on each upgrade, it's not only the "theme customization" methioned in this thread but also any others, such as "office support"... etc.

**Comment by alecyu** [comment]
> [@VipSaran](https://github.com/VipSaran) Unfortunately this plugin is not included in our installation package, so it needs to be reinstalled after every DBeaver update. Adding it to the package has other issues, but we will return to this in the future

It is very annoying on every installed plugins have to be re-installed again, again and again on each upgrade, it's not only the "theme customization" methioned in this thread but also any others, such as "office support"... etc.
