### ISSUE TITLE
Appearance of the edited cell with the date data type

### ISSUE THREAD

**Issue by troizet** [dbeaver/dbeaver#16436]
#### System information: 
- Operating system: Ubuntu 20.04
- DBeaver version: 21.3.4.202202051448, 22.0.4.202205011839

#### Describe the problem you're observing:
The appearance of the edited cell with the date data type is different from cells with other data types.

https://user-images.githubusercontent.com/9607501/167280542-3c5e2c41-39e0-4001-b671-f2269b58adeb.mp4

**Comment by PILINING** [comment]
Hello, I'd like to work on this issue.

**Comment by PILINING** [comment]
Hello, I'd like to work on this issue. 😃

**Comment by PILINING** [comment]
It seems that this issue is due to the date or time type not having a method like Text.selectAll() that can be called directly.
So my idea is to add a similar method to the CustomTimeEditor for all-selecting the contents of a cell of the date type.
It seems that the issue is solved through it.

https://user-images.githubusercontent.com/58755868/170418611-eac1d8f4-68c1-4d22-ace1-525ccd29a38f.mp4

**Comment by troizet** [comment]
This issue is still unresolved, the cell borders are still displayed differently.

 Operating system: Ubuntu 20.04.4 LTS
 DBeaver version: 22.1.0.202206051253


https://user-images.githubusercontent.com/9607501/174433678-d1c5e360-bbd7-4f26-95c1-47142f1021ba.mp4
