### ISSUE TITLE
External schemas not listed correctly in the Navigator Pane

### ISSUE THREAD

**Issue by AnnaGerlich** [dbeaver/dbeaver#19288]
### Description

External schemas are not recognized correctly in the 23.0.0 version. 

In the Navigator pane external schemas do not contain any tables. At the same time it is possible to query on the external tables so the connection itself is working correctly. 
- Usually in the previous versions there was a different icon that marks external schemas - this time the icon for external schema is the same as next to the non-external schemas. 
- There is no table visible under Tables in the external schema (they were visible in the previous versions).
- External schema is listed in the `SELECT * FROM svv_external_schemas` and it's possible to query on its tables. But it's not visible in the Navigator pane. 
- There are no proposals when I try to query on the external tables, but query works when typed manually

I assume it might be caused by https://github.com/dbeaver/dbeaver/commit/da9dd68aab1677d16f6ef46f0699a463cded31d2

### DBeaver Version

23.0.0

### Operating System

Windows11

### Database and driver

1. Redshift
2. com.amazon.redshift.jdbc42.Driver

### Steps to reproduce

1. Connect to Redshift using default HOST settings with provided: 
- Host/Instance
- Database
- Username
- Password
2.  Once connected I can see a list of all schemas, including the external one, but the Navigator Pane doesn't show the external schema's content.

**Comment by serge-rider** [comment]
Now DBeaver uses query `SELECT * FROM svv_external_schemas WHERE databasename=?`
Otherwise external schemas are duplicated in all databases (in case of multidatabase mode).

Current behavior seems to be more correct.

WDYT?

**Comment by AnnaGerlich** [comment]
In the current setup none of the schemas appear as an external and it's not possible to see any external table in the content. Navigator pane should allow for browsing all of the db content, right? 

I'm working with only 1 database for now.

**Comment by ciberboy** [comment]
This issue has been resolved with 23.0.1 for Amazon AWS database, but remains for Azure Databricks. I would suggest to re-open this issue

**Comment by mike-wilson-tubi** [comment]
Putting my two cents here, I am seeing this issue with community edition 24.0.1.202403241413 using Redshift JDBC driver 2.1.0.26.  Tables under external schemas are empty in the UI.

**Comment by gchalain** [comment]
Hello,
I'm having the same issue with 24.1.1.202406240959 using JDBC PostGressql driver 42.7.2.
Any news?
Thanks

**Comment by Jasmin1384** [comment]
I am facing same issue with 23.1.1 and 25.0.1 version. Tried different version of jdbc drivers as well jdbc42-2.1.0.26 ,  jdbc42-2.1.0.30,  jdbc42-2.1.0.32. Still face the same issue. Can you tell which version of dbeaver and jdbc I should use to resolve this?
