### ISSUE TITLE
SWT library missing error after 23 update

### ISSUE THREAD

**Issue by petursig** [dbeaver/dbeaver#19326]
### Description

After updating to the latest version 23.0 I can no longer start dbeaver
Tried uninstalling and reinstalling, it did not fix the issue, the logs say
"Caused by: java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: "

full log:

!SESSION 2023-03-10 11:06:12.096 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.12
java.vendor=Eclipse Foundation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.osgi 4 0 2023-03-10 11:06:12.953
!MESSAGE An error occurred while automatically activating bundle org.eclipse.ui.ide (155).
!STACK 0
org.osgi.framework.BundleException: Exception in org.eclipse.ui.internal.ide.IDEWorkbenchPlugin.start() of bundle org.eclipse.ui.ide.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:839)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:767)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1032)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:371)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:513)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:570)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:335)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:397)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:41)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:496)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.getRecentWorkspaces(DBeaverApplication.java:383)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.setIDEWorkspace(DBeaverApplication.java:359)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:209)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
Caused by: java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	C:\Users\PéturSigurðsson\.eclipse\org.jkiss.dbeaver.product_23.0.0_1535670467_win32_win32_x86_64\configuration\org.eclipse.osgi\145\0\.cp\swt-win32-4956r13.dll: Can't find dependent libraries
	no swt-win32 in java.library.path: [C:\Program Files\DBeaver, C:\Windows\Sun\Java\bin, C:\Windows\system32, C:\Windows, C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin, C:\Windows\system32, C:\Windows, C:\Windows\System32\Wbem, C:\Windows\System32\WindowsPowerShell\v1.0\, C:\Windows\System32\OpenSSH\, C:\Program Files\dotnet\, C:\Program Files\Microsoft SQL Server\150\Tools\Binn\, C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\, C:\Program Files\PuTTY\, C:\Program Files\Docker\Docker\resources\bin, C:\ProgramData\DockerDesktop\version-bin, C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR, C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\, C:\Program Files (x86)\Microsoft SQL Server\160\DTS\Binn\, C:\Program Files\Azure Data Studio\bin, C:\Program Files (x86)\GitExtensions\, C:\Program Files\Git\cmd, C:\Users\PÃ©turSigurÃ°sson\AppData\Local\Microsoft\WindowsApps, C:\Program Files\FireDaemon OpenSSL 3\bin, C:\Program Files\Azure Data Studio\bin, C:\Program Files\7-Zip, C:\Users\PÃ©turSigurÃ°sson\.dotnet\tools, C:\Users\PÃ©turSigurÃ°sson\AppData\Local\Programs\Microsoft VS Code\bin, .]
	no swt in java.library.path: [C:\Program Files\DBeaver, C:\Windows\Sun\Java\bin, C:\Windows\system32, C:\Windows, C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin, C:\Windows\system32, C:\Windows, C:\Windows\System32\Wbem, C:\Windows\System32\WindowsPowerShell\v1.0\, C:\Windows\System32\OpenSSH\, C:\Program Files\dotnet\, C:\Program Files\Microsoft SQL Server\150\Tools\Binn\, C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\, C:\Program Files\PuTTY\, C:\Program Files\Docker\Docker\resources\bin, C:\ProgramData\DockerDesktop\version-bin, C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR, C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\, C:\Program Files (x86)\Microsoft SQL Server\160\DTS\Binn\, C:\Program Files\Azure Data Studio\bin, C:\Program Files (x86)\GitExtensions\, C:\Program Files\Git\cmd, C:\Users\PÃ©turSigurÃ°sson\AppData\Local\Microsoft\WindowsApps, C:\Program Files\FireDaemon OpenSSL 3\bin, C:\Program Files\Azure Data Studio\bin, C:\Program Files\7-Zip, C:\Users\PÃ©turSigurÃ°sson\.dotnet\tools, C:\Users\PÃ©turSigurÃ°sson\AppData\Local\Programs\Microsoft VS Code\bin, .]
	C:\Users\PéturSigurðsson\.swt\lib\win32\x86_64\swt-win32-4956r13.dll: Can't find dependent libraries
	Can't load library: C:\Users\PéturSigurðsson\.swt\lib\win32\x86_64\swt-win32.dll
	Can't load library: C:\Users\PéturSigurðsson\.swt\lib\win32\x86_64\swt.dll
	C:\Users\PéturSigurðsson\.swt\lib\win32\x86_64\swt-win32-4956r13.dll: Can't find dependent libraries

	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:346)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:255)
	at org.eclipse.swt.internal.C.<clinit>(C.java:19)
	at org.eclipse.swt.internal.win32.STARTUPINFO.<clinit>(STARTUPINFO.java:42)
	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:148)
	at org.eclipse.ui.internal.ide.IDEWorkbenchPlugin.createProblemsViews(IDEWorkbenchPlugin.java:390)
	at org.eclipse.ui.internal.ide.IDEWorkbenchPlugin.start(IDEWorkbenchPlugin.java:347)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:818)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:810)
	... 30 more
Root exception:
java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	C:\Users\PéturSigurðsson\.eclipse\org.jkiss.dbeaver.product_23.0.0_1535670467_win32_win32_x86_64\configuration\org.eclipse.osgi\145\0\.cp\swt-win32-4956r13.dll: Can't find dependent libraries
	no swt-win32 in java.library.path: [C:\Program Files\DBeaver, C:\Windows\Sun\Java\bin, C:\Windows\system32, C:\Windows, C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin, C:\Windows\system32, C:\Windows, C:\Windows\System32\Wbem, C:\Windows\System32\WindowsPowerShell\v1.0\, C:\Windows\System32\OpenSSH\, C:\Program Files\dotnet\, C:\Program Files\Microsoft SQL Server\150\Tools\Binn\, C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\, C:\Program Files\PuTTY\, C:\Program Files\Docker\Docker\resources\bin, C:\ProgramData\DockerDesktop\version-bin, C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR, C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\, C:\Program Files (x86)\Microsoft SQL Server\160\DTS\Binn\, C:\Program Files\Azure Data Studio\bin, C:\Program Files (x86)\GitExtensions\, C:\Program Files\Git\cmd, C:\Users\PÃ©turSigurÃ°sson\AppData\Local\Microsoft\WindowsApps, C:\Program Files\FireDaemon OpenSSL 3\bin, C:\Program Files\Azure Data Studio\bin, C:\Program Files\7-Zip, C:\Users\PÃ©turSigurÃ°sson\.dotnet\tools, C:\Users\PÃ©turSigurÃ°sson\AppData\Local\Programs\Microsoft VS Code\bin, .]
	no swt in java.library.path: [C:\Program Files\DBeaver, C:\Windows\Sun\Java\bin, C:\Windows\system32, C:\Windows, C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin, C:\Windows\system32, C:\Windows, C:\Windows\System32\Wbem, C:\Windows\System32\WindowsPowerShell\v1.0\, C:\Windows\System32\OpenSSH\, C:\Program Files\dotnet\, C:\Program Files\Microsoft SQL Server\150\Tools\Binn\, C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\, C:\Program Files\PuTTY\, C:\Program Files\Docker\Docker\resources\bin, C:\ProgramData\DockerDesktop\version-bin, C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR, C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\, C:\Program Files (x86)\Microsoft SQL Server\160\DTS\Binn\, C:\Program Files\Azure Data Studio\bin, C:\Program Files (x86)\GitExtensions\, C:\Program Files\Git\cmd, C:\Users\PÃ©turSigurÃ°sson\AppData\Local\Microsoft\WindowsApps, C:\Program Files\FireDaemon OpenSSL 3\bin, C:\Program Files\Azure Data Studio\bin, C:\Program Files\7-Zip, C:\Users\PÃ©turSigurÃ°sson\.dotnet\tools, C:\Users\PÃ©turSigurÃ°sson\AppData\Local\Programs\Microsoft VS Code\bin, .]
	C:\Users\PéturSigurðsson\.swt\lib\win32\x86_64\swt-win32-4956r13.dll: Can't find dependent libraries
	Can't load library: C:\Users\PéturSigurðsson\.swt\lib\win32\x86_64\swt-win32.dll
	Can't load library: C:\Users\PéturSigurðsson\.swt\lib\win32\x86_64\swt.dll
	C:\Users\PéturSigurðsson\.swt\lib\win32\x86_64\swt-win32-4956r13.dll: Can't find dependent libraries

	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:346)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:255)
	at org.eclipse.swt.internal.C.<clinit>(C.java:19)
	at org.eclipse.swt.internal.win32.STARTUPINFO.<clinit>(STARTUPINFO.java:42)
	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:148)
	at org.eclipse.ui.internal.ide.IDEWorkbenchPlugin.createProblemsViews(IDEWorkbenchPlugin.java:390)
	at org.eclipse.ui.internal.ide.IDEWorkbenchPlugin.start(IDEWorkbenchPlugin.java:347)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:818)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:810)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:767)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1032)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:371)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:513)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:570)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:335)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:397)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:41)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:496)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.getRecentWorkspaces(DBeaverApplication.java:383)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.setIDEWorkspace(DBeaverApplication.java:359)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:209)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

!ENTRY org.eclipse.osgi 4 0 2023-03-10 11:06:12.997
!MESSAGE Application error
!STACK 1
java.lang.NoClassDefFoundError: org/eclipse/ui/internal/ide/ChooseWorkspaceData
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.getRecentWorkspaces(DBeaverApplication.java:383)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.setIDEWorkspace(DBeaverApplication.java:359)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:209)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
Caused by: java.lang.ClassNotFoundException: An error occurred while automatically activating bundle org.eclipse.ui.ide (155).
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:126)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:570)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:335)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:397)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:41)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:496)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 15 more
Caused by: org.osgi.framework.BundleException: Exception in org.eclipse.ui.internal.ide.IDEWorkbenchPlugin.start() of bundle org.eclipse.ui.ide.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:839)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:767)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1032)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:371)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:513)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	... 23 more
Caused by: java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	C:\Users\PéturSigurðsson\.eclipse\org.jkiss.dbeaver.product_23.0.0_1535670467_win32_win32_x86_64\configuration\org.eclipse.osgi\145\0\.cp\swt-win32-4956r13.dll: Can't find dependent libraries
	no swt-win32 in java.library.path: [C:\Program Files\DBeaver, C:\Windows\Sun\Java\bin, C:\Windows\system32, C:\Windows, C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin, C:\Windows\system32, C:\Windows, C:\Windows\System32\Wbem, C:\Windows\System32\WindowsPowerShell\v1.0\, C:\Windows\System32\OpenSSH\, C:\Program Files\dotnet\, C:\Program Files\Microsoft SQL Server\150\Tools\Binn\, C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\, C:\Program Files\PuTTY\, C:\Program Files\Docker\Docker\resources\bin, C:\ProgramData\DockerDesktop\version-bin, C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR, C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\, C:\Program Files (x86)\Microsoft SQL Server\160\DTS\Binn\, C:\Program Files\Azure Data Studio\bin, C:\Program Files (x86)\GitExtensions\, C:\Program Files\Git\cmd, C:\Users\PÃ©turSigurÃ°sson\AppData\Local\Microsoft\WindowsApps, C:\Program Files\FireDaemon OpenSSL 3\bin, C:\Program Files\Azure Data Studio\bin, C:\Program Files\7-Zip, C:\Users\PÃ©turSigurÃ°sson\.dotnet\tools, C:\Users\PÃ©turSigurÃ°sson\AppData\Local\Programs\Microsoft VS Code\bin, .]
	no swt in java.library.path: [C:\Program Files\DBeaver, C:\Windows\Sun\Java\bin, C:\Windows\system32, C:\Windows, C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin, C:\Windows\system32, C:\Windows, C:\Windows\System32\Wbem, C:\Windows\System32\WindowsPowerShell\v1.0\, C:\Windows\System32\OpenSSH\, C:\Program Files\dotnet\, C:\Program Files\Microsoft SQL Server\150\Tools\Binn\, C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\, C:\Program Files\PuTTY\, C:\Program Files\Docker\Docker\resources\bin, C:\ProgramData\DockerDesktop\version-bin, C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR, C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\, C:\Program Files (x86)\Microsoft SQL Server\160\DTS\Binn\, C:\Program Files\Azure Data Studio\bin, C:\Program Files (x86)\GitExtensions\, C:\Program Files\Git\cmd, C:\Users\PÃ©turSigurÃ°sson\AppData\Local\Microsoft\WindowsApps, C:\Program Files\FireDaemon OpenSSL 3\bin, C:\Program Files\Azure Data Studio\bin, C:\Program Files\7-Zip, C:\Users\PÃ©turSigurÃ°sson\.dotnet\tools, C:\Users\PÃ©turSigurÃ°sson\AppData\Local\Programs\Microsoft VS Code\bin, .]
	C:\Users\PéturSigurðsson\.swt\lib\win32\x86_64\swt-win32-4956r13.dll: Can't find dependent libraries
	Can't load library: C:\Users\PéturSigurðsson\.swt\lib\win32\x86_64\swt-win32.dll
	Can't load library: C:\Users\PéturSigurðsson\.swt\lib\win32\x86_64\swt.dll
	C:\Users\PéturSigurðsson\.swt\lib\win32\x86_64\swt-win32-4956r13.dll: Can't find dependent libraries

	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:346)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:255)
	at org.eclipse.swt.internal.C.<clinit>(C.java:19)
	at org.eclipse.swt.internal.win32.STARTUPINFO.<clinit>(STARTUPINFO.java:42)
	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:148)
	at org.eclipse.ui.internal.ide.IDEWorkbenchPlugin.createProblemsViews(IDEWorkbenchPlugin.java:390)
	at org.eclipse.ui.internal.ide.IDEWorkbenchPlugin.start(IDEWorkbenchPlugin.java:347)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:818)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:810)
	... 30 more

### DBeaver Version

Community edition 23.0

### Operating System

windows 10 pro

### Steps to reproduce

Install version 23 on windows and try starting dbeaver

**Comment by E1izabeth** [comment]
Probably it's happening because the installation path contains non-latin characters.
Could you try installing DBeaver to another directory?

**Comment by petursig** [comment]
The installation directory is C:\Program Files\DBeaver
I was running the previous version fine untill the 23 update.

**Comment by Destrolaric** [comment]
@petursig, Could you let me know which update method was used?

**Comment by serge-rider** [comment]
I was able to reproduce this by installing DBeaver in a folder with non-latin letters in the name.

@petursig try to reinstall DBeaver. 
Log says that it tries to find libraries in your user folder (C:\Users\PéturSigurðsson) instead of C:\Program Files\DBeaver.
You may need to delete previous DBeaver installation completely first (your data won't be lost)

**Comment by serge-rider** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=464414 (bug in Eclipse)
https://stackoverflow.com/questions/73665603/java-doesnt-recognize-unicode-character-in-path-on-windows-11 (bug in Java)

In fact being installed in a folder with Unicode characters in its name Java won't start. This problem was fixed in Java 19 (https://bugs.openjdk.org/browse/JDK-4488646) but we won't migrate to it this year.

Solution: install DBeaver for all users ("C:\Program Files\DBeaver") or in some other directory like `C:\Apps\DBeaver`.

**Comment by petursig** [comment]
In my case, the installation directory is C:\Program Files\DBeaver
But my User directory is C:\Users\PéturSigurðsson which is enough to cause this bug.
Some components seem to be installed into the users directory and fail on startup

**Comment by petursig** [comment]
Reinstalling for all users did not fix this issue for me. I did a uninstall, and deleted the dbeaver directory before installing again.
What I finally did to solve this was, I found the files, swt-gdip-win32-4956r13.dll and swt-win32-4956r13.dll
copied them to the C:/Program Files/DBeaver directory and renamed them to swt-gdip-win32.dll and swt-win32.dll
This fixed the issue for me and I can run DBeaver again.

**Comment by E1izabeth** [comment]
Thank you for investigation.

**Comment by E1izabeth** [comment]
Is the issue still actual for the latest DBeaver version?

**Comment by arhayka** [comment]
It's been a while since there has been an update here. Please let me know if the issue is still present and provide additional information.
