### ISSUE TITLE
Cannot complete the install DBeaver IDE 23.0.0.202303151400 on Eclipse IDE for Java Developers 4.27.0.20230309-1200

### ISSUE THREAD

**Issue by prja-b2b-one** [dbeaver/dbeaver#19389]
### Description

Installation / Update of DBeaver IDE 23.0.0.202303151400 on Eclipse IDE for Java Developers 4.27.0.20230309-1200 fail with:
```
Cannot complete the install because of a conflicting dependency.
  Software being installed: DBeaver IDE 23.0.0.202303151400 (org.jkiss.dbeaver.ide.feature.feature.group 23.0.0.202303151400)
  Software currently installed: Eclipse IDE for Java Developers 4.27.0.20230309-1200 (epp.package.java 4.27.0.20230309-1200)
  Only one of the following can be installed at once: 
    Quick Search 1.1.500.v20230129-1959 (org.eclipse.text.quicksearch 1.1.500.v20230129-1959)
    Quick Search 1.1.300.v20211203-1705 (org.eclipse.text.quicksearch 1.1.300.v20211203-1705)
    Quick Search 1.1.400.v20221023-0941 (org.eclipse.text.quicksearch 1.1.400.v20221023-0941)
  Cannot satisfy dependency:
    From: Eclipse IDE for Java Developers 4.27.0.20230309-1200 (epp.package.java 4.27.0.20230309-1200)
    To: org.eclipse.equinox.p2.iu; org.eclipse.platform.feature.group [4.27.0.v20230302-0300,4.27.0.v20230302-0300]
  Cannot satisfy dependency:
    From: Eclipse Platform 4.27.0.v20230302-0300 (org.eclipse.platform.feature.group 4.27.0.v20230302-0300)
    To: org.eclipse.equinox.p2.iu; org.eclipse.text.quicksearch [1.1.500.v20230129-1959,1.1.500.v20230129-1959]
  Cannot satisfy dependency:
    From: DBeaver Local Standalone Application 23.0.0.202303151400 (org.jkiss.dbeaver.app.local.feature.feature.group 23.0.0.202303151400)
    To: org.eclipse.equinox.p2.iu; org.eclipse.text.quicksearch [1.1.400.v20221023-0941,1.1.400.v20221023-0941]
  Cannot satisfy dependency:
    From: DBeaver IDE 23.0.0.202303151400 (org.jkiss.dbeaver.ide.feature.feature.group 23.0.0.202303151400)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.app.local.feature.feature.group [23.0.0.202303151400,23.0.0.202303151400]
```

### DBeaver Version

Community Edition v 23.0.0

### Operating System

LinuxMint (Ubuntu) v 21.1

### Database and driver

none

### Steps to reproduce

1. Open shop web page: https://marketplace.eclipse.org/content/dbeaver
2. Drag to your running Eclipse* workspace. *Requires Eclipse Marketplace Client
3. Eclipse trying to find solution, then giving "Cannot complete the install because of a conflicting dependency...."

### Additional context

None - clean eclipse from distribution

**Comment by E1izabeth** [comment]
Reproduced on Eclipse 2023-03
![image](https://user-images.githubusercontent.com/28875055/225599093-44af2b0e-7859-4c78-9f81-14a6efd77490.png)

**Comment by Destrolaric** [comment]
@prja-b2b-one Hi, DBeaver currently has not been updated to be compatible with the newest Eclipse version.

**Comment by RoiSoleil** [comment]
Same problem ;)

**Comment by serge-rider** [comment]
Fixed (quicksearch shouldn't be part of DBeaver plugin)

**Comment by vgiorgi** [comment]
Thank you!

**Comment by RoiSoleil** [comment]
Nice ! No more problems for updating Eclipse in the future ;)

**Comment by Matvey16** [comment]
Verified

**Comment by markscottwright** [comment]
I'm still experiencing this today (2023-03-21).  Am I doing something wrong?  

```
Cannot complete the install because of a conflicting dependency.
  Software being installed: DBeaver IDE 23.0.0.202303151400 (org.jkiss.dbeaver.ide.feature.feature.group 23.0.0.202303151400)
  Software currently installed: Eclipse Platform 4.27.0.v20230302-0300 (org.eclipse.platform.feature.group 4.27.0.v20230302-0300)
  Only one of the following can be installed at once: 
    Quick Search 1.1.500.v20230129-1959 (org.eclipse.text.quicksearch 1.1.500.v20230129-1959)
    Quick Search 1.1.400.v20221023-0941 (org.eclipse.text.quicksearch 1.1.400.v20221023-0941)
  Cannot satisfy dependency:
    From: Eclipse Platform 4.27.0.v20230302-0300 (org.eclipse.platform.feature.group 4.27.0.v20230302-0300)
    To: org.eclipse.equinox.p2.iu; org.eclipse.text.quicksearch [1.1.500.v20230129-1959,1.1.500.v20230129-1959]
  Cannot satisfy dependency:
    From: DBeaver Local Standalone Application 23.0.0.202303151400 (org.jkiss.dbeaver.app.local.feature.feature.group 23.0.0.202303151400)
    To: org.eclipse.equinox.p2.iu; org.eclipse.text.quicksearch [1.1.400.v20221023-0941,1.1.400.v20221023-0941]
  Cannot satisfy dependency:
    From: DBeaver IDE 23.0.0.202303151400 (org.jkiss.dbeaver.ide.feature.feature.group 23.0.0.202303151400)
    To: org.eclipse.equinox.p2.iu; org.jkiss.dbeaver.app.local.feature.feature.group [23.0.0.202303151400,23.0.0.202303151400]
```

Eclipse version:
```
Eclipse IDE for Enterprise Java and Web Developers (includes Incubating components)

Version: 2023-03 (4.27.0)
Build id: 20230309-1520
```

**Comment by E1izabeth** [comment]
The fix will be available with the next release.
