### ISSUE TITLE
Autocomplete function stops working when use the command "group_concat"

### ISSUE THREAD

**Issue by fizaza** [dbeaver/dbeaver#22336]
### Description

DBeaver Universal Database Manager version 23.3.1.202312241705. For MySQL MariaDB, the autocomplete function stops working, when comment a column using "/* */", or when use the command "group_concat".

### DBeaver Version

community version 23.3.1.202312241705

### Operating System

Windows 11 64bits

### Database and driver

My SQL MARIADB

### Steps to reproduce

The autocomplete function stops working, when comment a column using "/* */", or when use the command "group_concat".

**Comment by MashaKorax** [comment]
Hello, @fizaza. Can you provide your script?

**Comment by fizaza** [comment]
Hello. Shure..

#In this query the autocomplete function works fine
select
c.id,
c.name,
c.title,
c.updated
from contracts c
where date(c.updated) = date(sysdate())
;

/*
Using comments with asterisk and diagonal at the beginning, the autocomplete function stops working
*/
select
c.id,
c.name,
c.title,
c.updated,
c.name
from contracts c
where date(c.updated) = date(sysdate())
;

#The next query when detect the sentence "(select group_concat.." autocomplete stops working, it works again when comment with # group_concat sentence.

select
c.id,
c.name,
c.title,
c.updated,
c.name
,(select group_concat(case
                       when cash_given_amount > 0 and points_given_amount > 0 then 'Dinero y Puntos'
                       when points_given_amount > 0 then 'Puntos'
                       when cash_given_amount > 0 then 'Dinero'
                       end SEPARATOR ', ')
   from order_products_rewards
   where order_id = c.order_id
   group by order_id) fdi
from contracts c
where date(c.updated) = date(sysdate())
;


All querys run fine, only the DBeaver autocomplete functions stops working..

**Comment by MashaKorax** [comment]
Thanks for your report!

**Comment by E1izabeth** [comment]
@fizaza 
Please try our latest version DBeaver 23.3.2 - autocompletion with multiline comments should be fixed

**Comment by E1izabeth** [comment]
The other issue roots are in the `SEPARATOR ', '` part of the query

**Comment by E1izabeth** [comment]
We should improve our parser to handle group_concat syntax better https://mariadb.com/kb/en/group_concat/

**Comment by fizaza** [comment]
Thanks, I stay tuned..

**Comment by fizaza** [comment]
Hi, I installed Dbeaver Community version 23.3.3.202401211839, the autocomplete still doesn't work when I include GROUP_CONCAT sentence. I attach another example:

#The autocomplete function on this query doesn't work, if you comment   ",GROUP_CONCAT(.."   line, then works fine..
select 
u.username
,u.lov_user_status
,GROUP_CONCAT(m.name ORDER BY m.name SEPARATOR ', ') modules
,u.created
,u.updated 
,u.lov_user_type
,u.last_login_date
,u.lov_user_status
,u.blocked
from users u
left join users_modules um on um.user_id = u.id
left join modules m on um.module_id = m.id
where 
u.lov_user_status = 'Active'
Group by u.id
;

**Comment by E1izabeth** [comment]
The fix is not available in 23.3.3, it will be available in the next version 23.3.4
