### ISSUE TITLE
First Time User

### ISSUE THREAD

**Issue by DFergFLA** [dbeaver/dbeaver#2293]
First time user.  DBever doe not start successfully.  I have no idea why.  Using ElementaryOS Loki

[dbever.log](https://github.com/serge-rider/dbeaver/files/1367226/dbever.log)

**Comment by serge-rider** [comment]
Hello,

Do you use the most recent version of DBeaver (4.2.2+)? This issue was resolved in #2247

**Comment by DFergFLA** [comment]
This is what I downloaded and installed.

![screenshot from 2017-10-09 19 50 32](https://user-images.githubusercontent.com/32622501/31363268-484c40aa-ad2b-11e7-96a0-152bc17f704c.jpeg)

**Comment by serge-rider** [comment]
Could you check - do you have line `--add-modules=ALL-SYSTEM` in dbeaver.ini file?

**Comment by DFergFLA** [comment]
I am now able to start dbever, but when I try to connect to a Firebird db I
get


[image: Inline image 1]

I tried looking up the problem.  I tried wirecrypt = Enabled.  I tried
disabled, still can't get it to work.

attached is my firebird.conf.  Maybe I am doing it wrong.

**Comment by serge-rider** [comment]
Please attach images/files directly on GitHub comment.

**Comment by tati-kru** [comment]
There isn't any activity about this ticket very long time. It will be closed. However, if you think that it is actual just let us know.
