### ISSUE TITLE
DBeaver - Press Tab to accept the autocomplete choice.

### ISSUE THREAD

**Issue by nya13** [dbeaver/dbeaver#2316]
Hi,

I'm not sure if there is a settings we can set the Tab key as the keyword confirmation in the SQL Explorer?  I'm used to pressing Tab in Visual Studio IDE.  Right now, we need to press Enter, which is fine, but it would be nice to also use the Tab key.  Thanks!

**Comment by serge-rider** [comment]
Not sure this is possible in Eclipse..

**Comment by PatriciaGomesB** [comment]
I miss this "feature" to because i'm used to press Enter to autocomplete It's more suitable for me to do that.

**Comment by Speirs47** [comment]
I would like to ask what's going on with this enhancement? I'm really looking forward to it. Keyword confirmation with **Enter** is just annoying because AFAIK only Eclipse use it.

**Comment by serge-rider** [comment]
Related Eclipse bugs:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=348857
https://bugs.eclipse.org/bugs/show_bug.cgi?id=367009

Although there is a patch which fixes this it looks like they are not going to change current behavior in near future.
Perhaps I need to make another patch by myself.

**Comment by WesJones127** [comment]
I would love a fix for this as well.  Enter key is very strange for auto-complete, would prefer to use the Tab key.

**Comment by spinjector** [comment]
I would add that all versions of VB that I'm familiar with (Dot-Net, VB6, and VBA), SPACE also works to select an item from auto-complete. In fact, this is my preference, since it also inserts a space after the chosen item. This is the only key I've used for this purpose 20 years. Until I read this post, I didn't know TAB was also an option. 

Regarding how this operates in Eclipse/DBeaver, perhaps it could be added to the existing "hotkey engine", or if an extra "picker" is added, give the user the option to select from a variety of keys for it.

**Comment by lreficent** [comment]
Any new here? Is this feature going to be added? I'd love it too!

**Comment by nicchristeller** [comment]
Got frustrated by this and wrote a workaround using [AutoHotKey](https://www.autohotkey.com) that (surprisingly) works so smoothly that I forgot this was an issue, YMMV:
```
; tab to autocomplete in DBeaver
#IfWinActive, ahk_exe dbeaver.exe
	~Tab::
		Loop 15 {
			Sleep 10
			ControlGetFocus, focusedControl, A
			if (focusedControl = "SysListView321") {
				Send {Enter}
				break
			}
		}
	return
#IfWinActive
return
```

**Comment by insightfulquery** [comment]
Bump for this! Please add this as a feature, best if you make the auto-complete key configurable so everyone can choose their favorite!

nicchristeller's solution works really well! Thanks! The only problem with this solution is that now both enter and tab autocomplete, so if you are at the end of a line, done typing, and don't want autocomplete, you have to press space before you are allowed to press enter to go to the next line. Of course, most of the time the autocomplete will be just fine at that point, so you just have to hit enter twice, once to autocomplete and once to go to the new line. Not perfect, but not bad for a workaraound!

**Comment by DDriggs00** [comment]
Another bump. This would be an amazing feature.

**Comment by WatzlCe** [comment]
Leaving another bumb. Would be awesome to see that.

**Comment by eliliam** [comment]
Yet another bump on this, tab completion is an industry standard at this point, whereas enter completion is the odd one out. Really loving dbeaver, but not having this feature makes writing SQL scripts kind of an awkward task.

**Comment by p91paul** [comment]
@eliliam that "industry standard" thing looks a bit broad. Apart from bash, that also employs a very different type of completion, I've never seen it.

**Comment by Speirs47** [comment]
@p91paul I would say it's quite the opposite. I've never seen an app that would force using enter for autocompletion apart from Eclipse. I've seen that both works but absolutely never forcing just enter.

**Comment by cryptedx** [comment]
> @p91paul I would say it's quite the opposite. I've never seen an app that would force using enter for autocompletion apart from Eclipse. I've seen that both works but absolutely never forcing just enter.

I have seen that in LibreOffice Calc and it really is annoying! Please change this behavior.

**Comment by nihirisuto** [comment]
Coming to DBeaver from SSMS & Azure Data Studio this is kind of driving me mad lol. I'd love the option at least, even if it's off by default.

For the record DBeaver is probably the most recommended cross-OS application for cross platform use in SQL Server environments where employees can use either a Mac or Windows. Chances are the majority of those workers are using SSMS where the tab completion is a thing. I know for a fact the job I recently interviewed for has both SSMS and DBeaver available to use on the work images they install on laptops, with SSMS being the more heavily used option and a lot of habits like relying on tab-completion would presumably bleed over when using DBeaver.

**Comment by spinjector** [comment]
This is off-topic, but...yes, DBeaver is freekin amazing. :)

**Comment by MKEbrew** [comment]
Definitely need tab completion.  Very confusing after using anything else.

**Comment by Austin1** [comment]
Does anyone know how to do what @nicchristeller did using AutoHotKey but on a Mac? Tried ot figure it out with Karabiner Elements but not having any luck. This issue really is messing with my brain.

https://github.com/dbeaver/dbeaver/issues/2316#issuecomment-532056640

**Comment by bombillazo** [comment]
+1

Totally breaks my productivity given Tab is commonly used in terminals, IDEs, etc for autocompletion

**Comment by cgage1** [comment]
+1 

Any update on adding this feature? I thought it would be something I could get used to but I simply cannot.  I'm a big fan of DBeaver but I find myself opening SSMS for my SQL Server DB connections these days due to this.

**Comment by eliliam** [comment]
Can we get someone from the team to address this? Is this ever going to happen or is it a lost cause? We just need an update, it's been five years since the issue was opened with no official response.

**Comment by Korkman** [comment]
+1
Just turned off enter to accept suggestions in vscode because I am constantly fighting suggestions (press escape) when all I want is a newline. Tab is the way to go for me. Such options would be a very welcome addition to DBeaver. Thanks for considering although the underlying framework doesn't make it easy!

**Comment by sourceful-alex** [comment]
This is an important feature to add. The Enter key is a horrible key for autocomplete, because it gets pressed at the end of each line of SQL. Half the time this results in unwanted autocomplete activation (typically when the line ends with a table or column alias). The Tab key, on the other hand, is ideal. There's no reason need a Tab character anywhere other than the start of a line, so no more accidental autocomplete.

**Comment by superclarkk** [comment]
Have been trying DBeaver for the first time over the last week. This issue is a deal-breaker for me. Please, team, give the user the freedom of choice.

Also, when you press Enter to accept a suggestion, it creates a new line. I can't imagine anyone thinking that's acceptable.

**Comment by superclarkk** [comment]
btw, there are some jar patches in [this eclipse ticket](https://bugs.eclipse.org/bugs/show_bug.cgi?id=348857). Is it possible to integrate them into DBeaver?

**Comment by WellspringCS** [comment]
It being a 5 year old request, if I am reading this right, sounds like the feature is in. So I'd like to be the first to raise a toast! TY!

**Comment by bombillazo** [comment]
Just tried it out and the feature is _almost_ there! :D It was awesome to see the suggestions lists, but one still has to press `Enter` to select the intellisense/autocomplete option listed, vs pressing `tab` to fill the best match.

**Comment by MKEbrew** [comment]
No wonder why I couldn't figure out how to turn it on.

**Comment by E1izabeth** [comment]
@bombillazo 
Currently the completion proposal is automatically inserted only if there is only one proposal.
I guess it may be a new feature request to auto insert the best match from many proposals.

**Comment by E1izabeth** [comment]
@MKEbrew it will be available in the next release and turned on by default.

**Comment by E1izabeth** [comment]
@bombillazo wait, when exactly do you need Enter?
I tried it out and I need to press only tab to choose autocomplete proposal.
![Animation](https://user-images.githubusercontent.com/28875055/201139780-88195dc5-4559-4d70-98c5-9d2e2a4f737b.gif)

P.S. Implemented feature is not available right now automatically.

**Comment by bombillazo** [comment]
Ooh, I thought it was enabled. I was using the old experience still then. How do I enable it?

**Comment by E1izabeth** [comment]
@bombillazo We just implemented this feature, so it will be available only since 22.2.5.

**Comment by DifficultNick** [comment]
That's great feature, thank you! But can I disable autocomplete on enter key?

**Comment by E1izabeth** [comment]
@DifficultNick no, it's not possible now

**Comment by Skintillion** [comment]
I still can't get it to work here:
![image](https://github.com/dbeaver/dbeaver/assets/1521506/334a2f38-ce01-49ee-943d-298c14177412)

**Comment by Matt-410** [comment]
It's been quite some time since the last post here but I too would like to suggest disabling autocomplete on enter key. TAB only if that option is selected.

**Comment by RealTimeSpaceman** [comment]
> It's been quite some time since the last post here but I too would like to suggest disabling autocomplete on enter key. TAB only if that option is selected.

- I too would like to see this. When I get to the end of a line and hit Enter, I'm unhappy with what *keeps* happening
