### ISSUE TITLE
Alt + X keeps showing queries in single tab mode after changing back to multiple tab mode

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#35194]
### Description

This issue is about changing between tab modes: single mode to multiple mode and vice versa.
If the tab with Results is not closed, the next query executions will take into account the mode the Results tab had, not the current mode from settings.
Seems like this can be related: #35187 but I'm not sure

### DBeaver Version

Community Edition 24.1.5-202408122322

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.2

### Steps to reproduce

https://github.com/user-attachments/assets/63ea918c-c038-4b89-9ca2-dc6a7e4b8500

**Comment by TB-HunBoka** [comment]
This one is fixed in early access version 24.1.5

**Comment by TB-HunBoka** [comment]
Also, running a single query after a multitab query, will only replace the result1 sub tab. The result 1 (2) and statistics 1 will be still there.
NVM, you linked your other bug ticket, which is basically the same as I experienced.

**Comment by E1izabeth** [comment]
Thank you for bug report

**Comment by E1izabeth** [comment]
I can't reproduce this issue anymore. I believe it's solved.
If I'm not right, please let me know

**Comment by ask9** [comment]
I think this issue is not fully fixed.
Please check this test case.

**Actual:**
The tab "Results 1" is shown.

**Expected:**
The tab "Results 1" should not be shown (it contains result set of previous execution with single tab mode).




https://github.com/user-attachments/assets/1d22a13e-c0f7-4705-8617-a7890ce63ead

**Comment by E1izabeth** [comment]
Thanks!
