### ISSUE TITLE
Cannot open after update 24.2.5 version

### ISSUE THREAD

**Issue by rizqymuha** [dbeaver/dbeaver#36261]
### Description

```
> Start Eclipse Jobs Mechanism [org.eclipse.core.jobs 3.15.400.v20240619-0602]
> Start Equinox Java Authentication and Authorization Service (JAAS) [org.eclipse.equinox.security 1.4.400.v20240702-1702]
> Start DBeaver Application Standalone [org.jkiss.dbeaver.ui.app.standalone 24.2.5.202411171748]
> Start Eclipse IDE UI Application [org.eclipse.ui.ide.application 1.5.500.v20240711-0817]
SWT OS.java Error: Failed to load swt-pi3, loading swt-pi4 as fallback.
```

### DBeaver Version

24.2.5

### Operating System

Ubuntu 24.04.1 LTS

**Comment by itoDyeli** [comment]
same. this worked

```
sudo snap revert dbeaver-ce
rm -rf ~/snap/dbeaver-ce/common/.cache
```

**Comment by rizqymuha** [comment]
It works, you saved my monday time, thank you.
So the latest version still has bugs?

**Comment by vassil-boumov-softavail** [comment]
Guys, this is not serious!

There was the same problem with 24.2.3!!!

**Comment by jkhas8** [comment]
Same with me. However, I can not revert with snap.

**Comment by rizqymuha** [comment]
> Guys, this is not serious!
> 
> There was the same problem with 24.2.3!!!

Yes, I have had this problem before, I couldn't find a solution, so I just waited for an update.
Do you know how to solve it without reverting to the previous version?

**Comment by kAlvaro** [comment]
Mine just upgraded to 24.2.4 and started crashing, so I think this problem is present in all recent versions. The safe version for me is 24.0.5.202405191503, released on 20 May 2024.

**Comment by malchikovma** [comment]
Here is stack trace:
[1731922651042.log](https://github.com/user-attachments/files/17798087/1731922651042.log)

**Comment by vassil-boumov-softavail** [comment]
> > Guys, this is not serious!
> > There was the same problem with 24.2.3!!!
> 
> Yes, I have had this problem before, I couldn't find a solution, so I just waited for an update. Do you know how to solve it without reverting to the previous version?

The solution required revert and offered above works for me. I don't have another solution (except switching to an alternative app)...

**Comment by iamaakashbasnet** [comment]
Same problem here

**Comment by E1izabeth** [comment]
Thanks for the bug report

**Comment by sitar777** [comment]
Temporary fixed by going to edge channel

`sudo snap install dbeaver-ce --channel=latest/edge`

BTW, revert not working for me

`error: cannot revert "dbeaver-ce": no revision to revert to`

**Comment by iagoholekdev** [comment]
> Temporary fixed by going to edge channel
> 
> `sudo snap install dbeaver-ce --channel=latest/edge`
> 
> BTW, revert not working for me
> 
> `error: cannot revert "dbeaver-ce": no revision to revert to`

worked for me also, thanks

**Comment by ThiagoOFC** [comment]
> same. this worked
> 
> ```
> sudo snap revert dbeaver-ce
> rm -rf ~/snap/dbeaver-ce/common/.cache
> ```

it worked here

**Comment by malchikovma** [comment]
Couldn't wait for snap release, reverted too. 

There is a bug in the snap, instead of stable it updates to the latest version. Not the first time when unstable release crashes dbeaver. How can we make snap use proper stable version?
![image](https://github.com/user-attachments/assets/cb5f034c-fffa-4d54-a68d-61f7b066654e)

**Comment by petr-hybler-ofti** [comment]
same here.. has been broken for several past months.. howcome it's not yet fixed?

now, it doesn't work at all!!! revert only gets me back to 24.2.4 which is broken too :(  and the edge channel doesn't work either

```
$ sudo snap install dbeaver-ce --channel=latest/edge
snap "dbeaver-ce" is already installed, see 'snap help refresh'
```

Details here: https://github.com/dbeaver/dbeaver/issues/36168#issuecomment-2458777668

[dbeaver.log](https://github.com/user-attachments/files/17803550/dbeaver.log)

**Comment by Matvey16** [comment]
Rereleased on stable chanel
Verified
