### ISSUE TITLE
DBeaver does not revert all changes after error.

### ISSUE THREAD

**Issue by tchibatron** [dbeaver/dbeaver#5903]
#### System information: 
- DBeaver version: 6.0.4
- Java version: 8
- Additional extensions: no

#### Connection specification:
- Database name and version: Postgres 11.2
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  No

#### Describe the problem you're observing:
DBeaver does not revert all changes after error.

#### Steps to reproduce, if exist:
Create table with one column and add a primary key constraint for this column.
Try to add the new column and add second constraint for the new column.
You will get an error about two constriant - it's correct.
Click revert.
New column was reverted, but is still present in view. It disappears only after refresh.
See the [video](https://www.dropbox.com/s/on7d5whmw2rm8fw/Kazam_screencast_00001.mp4?dl=0)

**Comment by uslss** [comment]
still actual (6.3.2)

**Comment by serge-rider** [comment]
Probably fixed in #8169

**Comment by uslss** [comment]
still reproducible

**Comment by serge-rider** [comment]
Probably fixed in #8426

**Comment by uslss** [comment]
still reproducible. Column disappears after refresh only

**Comment by serge-rider** [comment]
@uslss please attach some video with steps to reproduce

**Comment by uslss** [comment]
**STR**
1. Create Table with 1 column and one PK. Save
1. Create new column and PK for new column. Note: column name should be different with existing key, so we'll get error message about multiple PK, not about that pk with this name is already existed.
1. Revert changes. Check Columns tab - second column is still shown
![2020-06-17_16h35_32](https://user-images.githubusercontent.com/31996417/84905207-08206300-b0b9-11ea-82da-42d6d31a196d.gif)

**Comment by serge-rider** [comment]
Fixed.
Once DDL command (ALTER TABLE) was succesfully processed it is saved in the database.
In this example there are 2 commands:
- Column create
- Constraint create

Column is saved and persisted. Constraint is not.
Revert works correctly. But we didn't do Commit after successful commands. Now we do.

Note: we do not execute entire DDL in a single transaction because most of databases do not support it. Thus we trying to keep it solid across different databases.

**Comment by uslss** [comment]
verified
