### ISSUE TITLE
[postgres] in 6.1.4 sometimes drop statements fail on "syntax error"

### ISSUE THREAD

**Issue by pyrocks** [dbeaver/dbeaver#6440]
#### System information: 
- Operating system (distribution) and version: mac os
- DBeaver version: 6.1.4

#### Connection specification:
- Database name and version : postgres 11.2
- Driver name : default
- Do you use tunnels or proxies (SSH, SOCKS, etc)? not relevant

#### Describe the problem you're observing:
It appears that sometimes drop statement fail on syntax error because for some reason DBeaver wraps the drop in a select - see image below:
![image](https://user-images.githubusercontent.com/18515297/62466473-0fd56280-b79a-11e9-8e84-e2289d72ff93.png)

This never occurred in previous versions (pre-6.1.4).

#### Include any warning/errors/backtraces from the logs

```
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [42601]: ERROR: syntax error at or near "database_privs"
  Position: 31
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:467)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:407)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:405)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:849)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2776)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:98)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:146)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:96)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3271)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "database_privs"
  Position: 31
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:266)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 12 more

```

**Comment by pyrocks** [comment]
This does not happen all the time. it does happen every time I run this query , copy the generated `drop` statements and try to run them
```select proc.oid, proname, rl.rolname, pg_get_functiondef(proc.oid), 
       'DROP ' || CASE prokind WHEN 'f' THEN 'FUNCTION' WHEN 'p' THEN 'PROCEDURE' END || ' ' || proname || '(' || pg_get_function_identity_arguments(proc.oid) || ');'
from pg_proc proc
inner join pg_catalog.pg_namespace ns on (ns.oid=pronamespace)
inner join pg_catalog.pg_roles rl on (proc.proowner=rl.oid)
where ns.nspname='public'
and proname like '%priv%';```

If I then run a query (any query) and issue the same drop again - it works.

My question is where do the "select * from (...) z_q" is coming from. it's certainly not my code.

**Comment by lrweck** [comment]
Getting the same thing from VACUUM and ANALYZE commands:

![image](https://user-images.githubusercontent.com/26086198/62467345-e0a6fd00-b769-11e9-829b-4f510e5c8e73.png)

**Comment by serge-rider** [comment]
I still can't reproduce this.

@pyrocks @lrweck could you write a bit more info - how to reproduce this.
DBeaver wraps query if it thinks that there are some filters/orderings were applied. It is definitely a bug which we will fix asap, once I'll be able to reproduce it.

**Comment by pyrocks** [comment]
Like I mentioned it happens **every time** I run the query I posted earlier, copy the drop statements from the result grid, paste it in the editor and try to run them.
If I then run any query, and then the drop statements again - it works fine.

**Comment by lrweck** [comment]
It happens in the context menu tool, also:

![image](https://user-images.githubusercontent.com/26086198/62468322-2664c500-b76c-11e9-9f56-b50eab32912b.png)

![image](https://user-images.githubusercontent.com/26086198/62468338-311f5a00-b76c-11e9-98c6-b61565a765a8.png)

![image](https://user-images.githubusercontent.com/26086198/62468383-5318dc80-b76c-11e9-98d5-313cf4a49a7e.png)

**Comment by serge-rider** [comment]
@pyrocks 10x, I'll try it one more time
@lrweck Just vacuum on any table? no any other actions?

**Comment by lrweck** [comment]
ANALYZE and TRUNCATE are working.

**Comment by serge-rider** [comment]
Could you test this in the Early Access Version? (https://dbeaver.io/files/ea)

**Comment by pyrocks** [comment]
Will do tomorrow morning. Will update.

**Comment by lrweck** [comment]
I can't reproduce it anymore through pure SQL, but it still happens with the DBeaver tool:

![image](https://user-images.githubusercontent.com/26086198/62492159-2c769800-b7a4-11e9-94a2-4c09de572ee2.png)

**Comment by lrweck** [comment]
Trying to run VACUUM on multiple tables, gives this:

![image](https://user-images.githubusercontent.com/26086198/62492939-38635980-b7a6-11e9-8da0-665083b6b5f9.png)

**Comment by serge-rider** [comment]
@lrweck could you check what exact queries are executed by DBeaver (you can see them in Query Manager view)?

**Comment by lrweck** [comment]
Yes:

![image](https://user-images.githubusercontent.com/26086198/62493270-10c0c100-b7a7-11e9-926f-2b26355d46a8.png)

Old case of changing syntax.

VACUUM (VERBOSE,ANALYZE,etc) only works in v 9.x and up.

Old syntax is VACUUM FULL VERBOSE ANALYZE schema.table_name. In this case, I was using v8.3.

So, it's an unrelated problem to the original, where DBeaver was using a subquery to run the SQL.

**Comment by serge-rider** [comment]
@lrweck thanks, yes, it is a different problem than @pyrocks reported
Could you create a separate ticket about VACUUM problems?

**Comment by lrweck** [comment]
Done: #6448 

btw, it was happening to me, like I show in my first comment:

> Getting the same thing from VACUUM and ANALYZE commands:
> 
> ![image](https://user-images.githubusercontent.com/26086198/62467345-e0a6fd00-b769-11e9-829b-4f510e5c8e73.png)

**Comment by serge-rider** [comment]
Goog. It seems that problem with SQL wrapping was fixed.

**Comment by pyrocks** [comment]
I cannot reproduce it in Early Access Version

**Comment by serge-rider** [comment]
Thank you for testing.
We will release hotfix version today.

**Comment by kseniiaguzeeva** [comment]
The ticket is not reproduced anymore

**Comment by Pat28** [comment]
Wrapping SQL is still happening to me on the latest version from the Windows Store...which seems to be released on April 9 2019...hence an old version...switched to the Windows 64 bit installer which helped a lot.
