### ISSUE TITLE
How to move a connection to another proejct?

### ISSUE THREAD

**Issue by sryze** [dbeaver/dbeaver#6490]
#### System information: 
- Windows 10
- DBeaver version: 6.1.4

#### Connection specification:
- Database name and version

#### Describe your question:

This might be a dumb question but I cannot for the life of me figure out how to transfer / move a connection from on project (folder) to another project. I created a connection in General some time ago and I want to move it to a new project (let's say MyProject).

DBeaver won't let me drag it to MyProject, and it won't let me to copy and paste it either (it gets inserted into General when I click Paste).

What is the proper way to do this?

**Comment by serge-rider** [comment]
In fact copy-paste should work. I is actually a bug in one of recent versions. 
Thanks for bringing this up.

**Comment by serge-rider** [comment]
Also fixed drag-n-drop

**Comment by sryze** [comment]
Thanks!

**Comment by uslss** [comment]
Reopened.
Misalignment in behavior.
If connection is drag-and-drop from project that situated "higher" - it is replaced from one project to another. If it is d-n-d'ed to higher project - it is copied
![connections](https://user-images.githubusercontent.com/31996417/62898452-2a8d7580-bd5e-11e9-807c-a74905c46f04.gif)

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified

**Comment by benjamin-zach** [comment]
Neither drag&drop nor copy&paste seem to work when moving a folder containing connections from one project to another. Is this intended?
I'm using Version 22.2.3.202210231354

**Comment by angry-werner** [comment]
Somehow still doesn't work for me, on rhel 8 and with 23.0.2, neither copy and paste nor drag and drop

**Comment by nicholasvperry** [comment]
This also will not work for me. I imported my project file and cannot move it to another project. I also cannot add the connections to the database navigator.

**Comment by dembA7** [comment]
Drag and dropping a folder containing connections doesn't seem to work. Workaround is to create the folder in the destination project and drag and dropping the connections themselves into the new folder.
