### ISSUE TITLE
[PostgreSQL] Display privileges and default privileges in schema DDL

### ISSUE THREAD

**Issue by rbovard** [dbeaver/dbeaver#6565]
Hello,

Working on PostgreSQL schemas with DBeaver 6.1.4, I noticed that in the generated DDL for schemas the **privileges** and **default privileges** are not displayed.

**pgAdmin**

```
CREATE SCHEMA <schema> AUTHORIZATION <admin>;

GRANT ALL ON SCHEMA <schema> TO <admin>;
GRANT ALL ON SCHEMA <schema> TO <role_1>;
GRANT USAGE ON SCHEMA <schema> TO <role_2>;

ALTER DEFAULT PRIVILEGES IN SCHEMA <schema>
    GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES
    TO <role_1>;

ALTER DEFAULT PRIVILEGES IN SCHEMA <schema>
    GRANT SELECT ON TABLES
    TO <role_2>;

ALTER DEFAULT PRIVILEGES IN SCHEMA <schema>
    GRANT SELECT, UPDATE, USAGE ON SEQUENCES
    TO <role_1>;

ALTER DEFAULT PRIVILEGES IN SCHEMA <schema>
    GRANT SELECT, UPDATE, USAGE ON SEQUENCES
    TO <role_2>;

ALTER DEFAULT PRIVILEGES IN SCHEMA <schema>
    GRANT EXECUTE ON FUNCTIONS
    TO <role_1>;

ALTER DEFAULT PRIVILEGES IN SCHEMA <schema>
    GRANT EXECUTE ON FUNCTIONS
    TO <role_2>;

ALTER DEFAULT PRIVILEGES IN SCHEMA <schema>
    GRANT USAGE ON TYPES
    TO <role_1>;

ALTER DEFAULT PRIVILEGES IN SCHEMA <schema>
    GRANT USAGE ON TYPES
    TO <role_2>;
```

**DBeaver 6.1.4**

```
CREATE SCHEMA <schema> AUTHORIZATION <admin>;
```

As I can see, the missing statements are:
* `GRANT <what> ON SCHEMA <schema> TO <who>;`
* `ALTER DEFAULT PRIVILEGES IN SCHEMA <schema> GRANT <what-s> ON TABLES
    TO <who>;`

Is it possible to add these informations?

Thanks for your great work.

**Comment by nledenyi** [comment]
I also noticed the same some time back, however for Greenplum and not native Postgres. Would love to see it added so I can finally ditch pgadmin for good

**Comment by serge-rider** [comment]
Done.
As addition to #7266

**Comment by uslss** [comment]
verified

**Comment by rbovard** [comment]
I just tested on v7.0.0 and the content of the tab "source" on a schema is still:

```
CREATE SCHEMA <schema> AUTHORIZATION <admin>;
```

Am I missing something?

**Comment by rbovard** [comment]
Hello @uslss @serge-rider 

I've downloaded v7.1.0 and I still cannot see what I'm looking for...

Maybe something is not clear between us, I'm trying to see rights and default priviliges on schema in the source tab, like in PgAdmin (see my initial post). Or maybe it is avalaible somewhere else?

Thanks for your feedback.

**Comment by grassu** [comment]
Hello @uslss @serge-rider
I can confirm that in the current version 7.1.3 default privileges are missing on schema source tab.
Could you please reopen the issue?

Thanks in advance.

**Comment by uslss** [comment]
Doesn't Show Permissions button solve the issue?

**Comment by grassu** [comment]
Hello @usless,

thanks for your reply. Unfortunately not. 
There are only visible the "GRANT ..." entries:
```
GRANT ALL ON SCHEMA test TO test_admin;
GRANT USAGE ON SCHEMA test TO test_writegroup;
GRANT USAGE ON SCHEMA test TO test_readgroup;
```

Entries starting with "ALTER DEFAULT PRIVILEGES ..." are missing completely:
```
ALTER DEFAULT PRIVILEGES IN SCHEMA test
GRANT ALL ON TABLES TO test_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA test
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLES TO test_writegroup;
ALTER DEFAULT PRIVILEGES IN SCHEMA test
GRANT SELECT ON TABLES TO test_readgroup;
```
Same for functions, sequences, etc.

**Comment by rbovard** [comment]
Hi @uslss,

I just tested with `22.3.0` and unfortunately the default privileges are still missing.

Is it possible to reopen this issue please?

**Comment by rbovard** [comment]
I've opened an new issue for the missing default privileges https://github.com/dbeaver/dbeaver/issues/18854
