### ISSUE TITLE
.dbeaver folder created in every eclipse project, hanging UI on startup

### ISSUE THREAD

**Issue by aniefer** [dbeaver/dbeaver#6968]
#### System information: 
Windows 10
DBeaver IDE 6.2.0.201909221748 installed into existing Eclipse 4.14 install

#### Describe the problem you're observing:
On startup of eclipse, DBeaver scans the workspace and creates .dbeaver folders in every project that does not contain one.

I have ~400 projects in my workspace, all are under source control.  This creates 400 outgoing dirty changes that I need to revert because I'm not going to commit (empty) configuration settings for a tool that is not standard in my company.  This is a blocker for me, and I reverted to DBeaver 6.1 because of it.

This may also hang the UI for several minutes because it runs on the main thread and may be blocked by background jobs.  In particular, something like a build may block this for an extended period.

Java core dump shows the main thread  and another dbeaver background thread blocked in the JobManager.  It is unclear who owned the blocking job, it may have just completed because my UI unfroze very shortly after taking this dump.

3XMTHREADINFO      "main" J9VMThread:0x00000000028B9A00, omrthread_t:0x00000000028A6D90, java/lang/Thread:0x000000009A8CA620, state:CW, prio=6
3XMJAVALTHREAD            (java/lang/Thread getId:0x1, isDaemon:false)
3XMTHREADINFO1            (native thread ID:0x4368, native priority:0x6, native policy:UNKNOWN, vmstate:CW, vm thread flags:0x00080181)
3XMCPUTIME               CPU usage total: 16.171875000 secs, user: 11.718750000 secs, system: 4.453125000 secs, current category="Application"
3XMTHREADBLOCK     Waiting on: java/lang/Object@0x00000000A28B1AB0 Owned by: <unowned>
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=0 (0x0)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/lang/Object.wait(Native Method)
4XESTACKTRACE                at java/lang/Object.wait(Object.java:218(Compiled Code))
4XESTACKTRACE                at org/eclipse/core/internal/jobs/ThreadJob.waitForRun(ThreadJob.java:318(Compiled Code))
5XESTACKTRACE                   (entered lock: java/lang/Object@0x00000000A28B1AB0, entry count: 1)
4XESTACKTRACE                at org/eclipse/core/internal/jobs/ThreadJob.joinRun(ThreadJob.java:205)
4XESTACKTRACE                at org/eclipse/core/internal/jobs/ImplicitJobs.begin(ImplicitJobs.java:95)
4XESTACKTRACE                at org/eclipse/core/internal/jobs/JobManager.beginRule(JobManager.java:298)
4XESTACKTRACE                at org/eclipse/core/internal/resources/WorkManager.checkIn(WorkManager.java:124)
4XESTACKTRACE                at org/eclipse/core/internal/resources/Workspace.prepareOperation(Workspace.java:2241)
4XESTACKTRACE                at org/eclipse/core/internal/resources/Folder.create(Folder.java:90)
4XESTACKTRACE                at org/jkiss/dbeaver/registry/ProjectMetadata.getMetadataFolder(ProjectMetadata.java:107)
4XESTACKTRACE                at org/jkiss/dbeaver/registry/ProjectMetadata.ensureOpen(ProjectMetadata.java:151)
4XESTACKTRACE                at org/jkiss/dbeaver/registry/ProjectMetadata.getDataSourceRegistry(ProjectMetadata.java:159(Compiled Code))
4XESTACKTRACE                at org/jkiss/dbeaver/model/DBUtils.getAllRegistries(DBUtils.java:1822)
4XESTACKTRACE                at org/jkiss/dbeaver/ui/actions/datasource/DataSourceToolbarHandler.<init>(DataSourceToolbarHandler.java:104)
4XESTACKTRACE                at org/jkiss/dbeaver/core/WorkbenchContextListener.listenWindowEvents(WorkbenchContextListener.java:104)
4XESTACKTRACE                at org/jkiss/dbeaver/core/WorkbenchContextListener.<init>(WorkbenchContextListener.java:63)
4XESTACKTRACE                at org/jkiss/dbeaver/core/WorkbenchContextListener.registerInWorkbench(WorkbenchContextListener.java:278)
4XESTACKTRACE                at org/jkiss/dbeaver/core/DBeaverUI.lambda$0(DBeaverUI.java:129)
4XESTACKTRACE                at org/jkiss/dbeaver/core/DBeaverUI$$Lambda$456/000000001A367D80.run(Bytecode PC:4)
4XESTACKTRACE                at org/eclipse/swt/widgets/RunnableLock.run(RunnableLock.java:40)
4XESTACKTRACE                at org/eclipse/swt/widgets/Synchronizer.runAsyncMessages(Synchronizer.java:185)
5XESTACKTRACE                   (entered lock: org/eclipse/swt/widgets/RunnableLock@0x00000000A0855E90, entry count: 1)
4XESTACKTRACE                at org/eclipse/swt/widgets/Display.runAsyncMessages(Display.java:3963)

3XMTHREADINFO      "DBeaver: Keep-Alive monitor" J9VMThread:0x000000000453B800, omrthread_t:0x0000000015D3BA50, java/lang/Thread:0x00000000A2554680, state:CW, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x60, isDaemon:false)
3XMTHREADINFO1            (native thread ID:0x2344, native priority:0x5, native policy:UNKNOWN, vmstate:CW, vm thread flags:0x00000181)
3XMCPUTIME               CPU usage total: 0.500000000 secs, user: 0.453125000 secs, system: 0.046875000 secs, current category="Application"
3XMTHREADBLOCK     Waiting on: java/lang/Object@0x00000000A28B1AB0 Owned by: <unowned>
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=0 (0x0)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/lang/Object.wait(Native Method)
4XESTACKTRACE                at java/lang/Object.wait(Object.java:189)
4XESTACKTRACE                at org/eclipse/core/internal/jobs/ThreadJob.waitForRun(ThreadJob.java:316(Compiled Code))
5XESTACKTRACE                   (entered lock: java/lang/Object@0x00000000A28B1AB0, entry count: 1)
4XESTACKTRACE                at org/eclipse/core/internal/jobs/ThreadJob.joinRun(ThreadJob.java:205)
4XESTACKTRACE                at org/eclipse/core/internal/jobs/ImplicitJobs.begin(ImplicitJobs.java:95)
4XESTACKTRACE                at org/eclipse/core/internal/jobs/JobManager.beginRule(JobManager.java:298)
4XESTACKTRACE                at org/eclipse/core/internal/resources/WorkManager.checkIn(WorkManager.java:124)
4XESTACKTRACE                at org/eclipse/core/internal/resources/Workspace.prepareOperation(Workspace.java:2241)
4XESTACKTRACE                at org/eclipse/core/internal/resources/Folder.create(Folder.java:90)
4XESTACKTRACE                at org/jkiss/dbeaver/registry/ProjectMetadata.getMetadataFolder(ProjectMetadata.java:107)
4XESTACKTRACE                at org/jkiss/dbeaver/registry/ProjectMetadata.ensureOpen(ProjectMetadata.java:151)
4XESTACKTRACE                at org/jkiss/dbeaver/registry/ProjectMetadata.getDataSourceRegistry(ProjectMetadata.java:159(Compiled Code))
4XESTACKTRACE                at org/jkiss/dbeaver/runtime/jobs/KeepAliveJob.run(KeepAliveJob.java:65)
4XESTACKTRACE                at org/jkiss/dbeaver/model/runtime/AbstractJob.run(AbstractJob.java:103)
4XESTACKTRACE                at org/eclipse/core/internal/jobs/Worker.run(Worker.java:63)

**Comment by aniefer** [comment]
Regarding creating folders in all the projects, its seems reasonable that perhaps somewhere in here 
at org/jkiss/dbeaver/registry/ProjectMetadata.getMetadataFolder(ProjectMetadata.java:107)
at org/jkiss/dbeaver/registry/ProjectMetadata.ensureOpen(ProjectMetadata.java:151)
at org/jkiss/dbeaver/registry/ProjectMetadata.getDataSourceRegistry(ProjectMetadata.java:159(Compiled Code))
at org/jkiss/dbeaver/model/DBUtils.getAllRegistries(DBUtils.java:1822)

could be a check that the project contains the org.jkiss.dbeaver.DBeaverNature nature

**Comment by serge-rider** [comment]
Thanks for the bug report. This seems to be quite critical.
`.dbeaver` folder must be created only on demand (e.g. when you create a new connection in this project).

**Comment by serge-rider** [comment]
Fixed.
This code also involved in metadata structure migration, we'll need to test again.

**Comment by serge-rider** [comment]
New Early Access version (https://dbeaver.io/files/ea + Eclipse update site https://dbeaver.io/files/ea/update/dbeaver/) is ready. Please test

**Comment by aniefer** [comment]
I upgraded to 6.2.2.201910111357 and I no longer see the .dbeaver folders created.

Thanks for the fast response.

**Comment by gnikolaidis** [comment]
Hi, I have 22.2.3.202210231354 and the .dbeaver folders keep getting created in every project. I was unable to find a way to prevent this behavior. Is this because of metadata from older versions lingering arround?

**Comment by JRaue** [comment]
Hi, I confirm that problem persists in DBeaver IDE f. Eclipse V 22.2.4.202211061524 for projects without DBeaver, Clearly an annoyance and hopefully rather easy to fix.
