### ISSUE TITLE
Access Denied: Cannot Read /usr/bin When Installed as Snap

### ISSUE THREAD

**Issue by dsmithhayes** [dbeaver/dbeaver#7521]
#### System information: 
- Elementary OS 5.1
- DBeaver 6.3.1

#### Connection specification:
- MariaDB
- MySQL

#### Describe your question:
I am not able to read my system's `/usr/bin` path within DBeaver when it is installed through the Snap packaging system. I have A MySQL and MariaDB client on my local machine in that directory and would like to use DBeaver to dump databases. Is there any insight some one can provide?

I apologize if this is a technical limitation of Snap and does not belong here.

**Comment by CitizenBeta** [comment]
I can reproduce this on Ubuntu 19 when installed via "Ubuntu Software"

**Comment by galgalesh** [comment]
@dsmithhayes Thanks for your bug report. I'm looking to include the native clients in the snap. Are both the MySQL _and_ MariaDB clients required or is it ok to only include the MariaDB client?

**Comment by dsmithhayes** [comment]
@galgalesh Thank you, I am personally fine wit the MariaDB client, but I think it may be more valuable to include both.

**Comment by serge-rider** [comment]
MariaDB client included in new snap build. Thanks to @galgalesh

**Comment by uslss** [comment]
verified

**Comment by gsevla** [comment]
Same with postgres.

dveaver have no permission to access /usr/bin.

**Comment by galgalesh** [comment]
@gsevla Are you saying the dbeaver snap can't dump a postgres database?

**Comment by gsevla** [comment]
> @gsevla Are you saying the dbeaver snap can't dump a postgres database?

I didn't try to dump pg db. I'm saying dbeaver snap can't connect to pg db, because it's runner is located in / usr / bin, where dbeaver snap have no permission to access.

I already tested dbeaver flatpak and it haven't access to /usr/bin too. But I can install postgres dbeaver io from flatpak and access pg bin from flatpak folders so it works. If dbeaver snap have something like it, I doesn't know.

**Comment by galgalesh** [comment]
@gsevla Can you open a new issue for this? Specifically about you no being able to connect to postgres using the dbeaver snap. It's very unlikely dbeaver will ever get access to `/usr/bin` but all the required clients should be shipped inside of the snap.

**Comment by neuberoliveira** [comment]
same here, installed via snap install dbeaver-ce trying to dump a mysql database with no success.

As far as i can tell its related to strict confinement, because dbeaver need an local client to do the export, and because of snap confinement dbeaver cant reach the mysql client installed on my system

**Comment by galgalesh** [comment]
@neuberoliveira 

Where is this database you are trying to dump (on a remote server or on your computer?) and what is the error you are getting?

The original issue is fixed: the dbeaver snap now ships the client as part of the snap.

**Comment by JonathanAJ** [comment]
Same here in `/snap/` Ubuntu folder with mysql.
Dbeaver don't ask permission to me in initialize application.

**Comment by freddiedfre** [comment]
![Screenshot from 2020-06-29 20-52-00](https://user-images.githubusercontent.com/4942663/86038984-77e40580-ba4a-11ea-9134-23532ae2a8cd.png)

Same situation here. Used snap install on ubuntu 20.04

**Comment by galgalesh** [comment]
This could easily be fixed in the snap, and I'm happy to help the developers with this, but I can't do anything until this issue is fixed: https://github.com/dbeaver/dbeaver/issues/8774

**Comment by JonathanAJ** [comment]
I ran `.deb` file for dbeaver and executed fine!

**Comment by benjamindally** [comment]
> @gsevla Can you open a new issue for this and tag me in it? Specifically about you no being able to connect to postgres using the dbeaver snap. It's very unlikely dbeaver will ever get access to `/usr/bin` but all the required clients should be shipped inside of the snap.

Any idea if this issue being tracked or should I start a new issue for 'including PostgreSQL in the snap'? I see reference below to the .yaml issue, #8774, but not one to track PostgreSQL specifically.

**Comment by marceloimg93** [comment]
My case was an issue when trying to save a DUMP on a second HDD. I solved by following steps:

1st - open ubuntu software 
2nd - search for dbeaver-ce
3rd - after installed it, click Permissions
4th - check Read/write files on removable storage devices

Hope it might help someone in the future.

Cheers

**Comment by raiaman15** [comment]
Using .deb based installation and everything works perfectly (the specific issue for me was setting local client, required to perform the backup operation).

**Comment by thomich** [comment]
tried snap package on ubuntu 20.04 and also can't get native client running, even no permissions to /usr/bin..
installed -deb package from https://dbeaver.io/download/ and now all fine...

i just needed to set /usr/bin as native client home dir:
![image](https://user-images.githubusercontent.com/4398840/109018919-cff60900-76b8-11eb-8b92-66d6d8de9a23.png)

**Comment by dgills** [comment]
A hacky workaround to keep your snap and avoid reinstalling as .deb:

Just add the your **/usr/bin** (or wherever your DB client is) to your bookmarked folders in file explorer:

![dbeaver-snap-dir-issue](https://user-images.githubusercontent.com/2458526/116893809-638b0f00-abff-11eb-9e24-3ec1db782a98.png)

**Comment by artibyrd** [comment]
> A hacky workaround to keep your snap and avoid reinstalling as .deb:
> 
> Just add the your **/usr/bin** (or wherever your DB client is) to your bookmarked folders in file explorer:
> 
> ![dbeaver-snap-dir-issue](https://user-images.githubusercontent.com/2458526/116893809-638b0f00-abff-11eb-9e24-3ec1db782a98.png)

This actually worked to add the client home location somehow, but still gives me errors when actually attempting to do something like run a backup.  I'm using Postgres not MariaDB, and I still get an error like `Error executing process Utility 'pg_dump' not found in client home '/usr/bin' (/usr/bin)` because DBeaver still doesn't have permission to the perl script link in /usr/bin even with this location now added.

**Comment by rickdevops** [comment]
that wasnt fix yet?

**Comment by aditya-rewari** [comment]
I tried above mentioned steps.. didn't help though
So I just went the command line way
Sharing commands for MYSQL

**Create dump**
`mysqldump -u [username] -p -h [host] [databasename] > [dumpfile.sql]`

**Import Dump data**
`mysqldump -u [username] -p -h [host] [databasename] < [dumpfile.sql]`

**Import Dump data at localhost**
`mysqldump -u [username] -p [databasename] < [dumpfile.sql]`

PS: I self created the databasename while importing before using the command.

**Comment by jkpcguru** [comment]
This bug still exists

**Comment by uslss** [comment]
issue is tracked in #8508

**Comment by thomas-covenant** [comment]
snap is the biggest crap, uninstall snap version and use the deb package

**Comment by tarikhagustia** [comment]
same on Ubuntu 22

**Comment by IziumenkoViacheslav** [comment]
I changed folder to Download and everithing work.

**Comment by IziumenkoViacheslav** [comment]
I changed destination folder to Downloads and it works
![Screenshot from 2022-06-30 17-17-14](https://user-images.githubusercontent.com/35495499/176714528-2b8433a9-5919-461a-bb51-608afb939216.png)

**Comment by d-averkiev** [comment]
As it said above, the reason why snap version is not able to find/read the "local client" binaries is the strict confinement. But there is a way to workaround it:

1. Allow dbeaver-ce snap to read/write from removable media
![Screenshot from 2023-01-30 12-42-07](https://user-images.githubusercontent.com/8374182/215456662-f64295f6-973b-4e20-86a2-9cda91fc55c9.png)

2. Create a mount point in /mnt
`sudo mkdir /mnt/usr_bin`

3. Bind mount your binaries location (/usr/bin in my case) to newly created dir
`sudo mount --bind /usr/bin/ /mnt/usr_bin/`

4. Now you are able to set /mnt/usr_bin as your "local client" home
![Screenshot from 2023-01-30 12-43-40](https://user-images.githubusercontent.com/8374182/215456804-0bf3974d-e467-4a49-a174-c9f018c40beb.png)

**Comment by enricodevita** [comment]
also i

**Comment by dmozar** [comment]
1. For Ubuntu, download dbeaver deb installation from https://dbeaver.io/download and install. 

2. First find where is mysql installed with command: which mysql

3. If result is /usr/bin/mysql add client path without mysq, just /usr/bin

Run as sudo user in terminal with command: dbeaver to start application.

if you get error a dbeaver-ce permission error, you can execute command: sudo chmod +rx /usr/share/dbeaver-ce and start dbeaver again.
