### ISSUE TITLE
Statistics tab always becomes active when running a SQL script

### ISSUE THREAD

**Issue by quiescer** [dbeaver/dbeaver#7704]
Since DBeaver 6.3.2, each time I run a SQL script in the query editor, (by selecting the script text and then pressing Ctrl+Enter) the Statistics tab always becomes active, even when I previously had the database output tab active.

Additionally, the Statistics tab seems to contain no information, so doesn't seem to be helpful for running a SQL script.

I often run the same script multiple times with different bind parameters, so it is a little frustrating to have to repeatedly switch back to the Output tab from the Statistics tab.

Could it be reverted such that whichever tab in the lower pane is selected stays selected when running a SQL script.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by 18549** [comment]
This is annoying. When I'm developing a script and wanting to view the log output it switches to Statistics every time, even if the script doesn't output anything!

**Comment by serge-rider** [comment]
Fixed

**Comment by kseniiaguzeeva** [comment]
Verified

**Comment by jyinpci** [comment]
I am seeing this issue with 22.1.4 (but only for some instances of dbeaver).  After running a script, it always shows the <Statistics 1> tab.  I have to switch manually to the <Results 1> tab.  Is there a configuration that I can set to suppress this?  I have dbeaver (same version running on another connected to a different database), the default output tab is the <Results 1> tab.

**Comment by cesar-bsd-com-br** [comment]
I have the same problem with "statistics window" with version 22.1.5.

**Comment by devaib** [comment]
Same issue here with version 22.1.5 on Windows.

**Comment by neoman-titan** [comment]
Seems this has been fixed in 22.2.0!

**Comment by cesar-bsd-com-br** [comment]
Yes, solved with the version 22.2.0.

Thanks @titanlab

**Comment by jyinpci** [comment]
Hmmm, somehow it still happens to me in 22.2.0.

**Comment by anguis-datura** [comment]
> Hmmm, somehow it still happens to me in 22.2.0.

To repro just close result tab and statistic tab starts to appear after each script execution again, as workaround reopen DBeaver.

**Comment by bickgr** [comment]
Still having the same issue on Version 22.2.0.202209051344, when running a sql script with multiple queries, the statistics tab is still the default selected tab

**Comment by Obeydullah** [comment]
Still have the issue with version 22.2.0

**Comment by jyinpci** [comment]
I opened a new issue https://github.com/dbeaver/dbeaver/issues/17763 for this.  Please add your comments to the new issue.

**Comment by tongdong6953** [comment]
still happening in  Version 22.2.3.202210231354

**Comment by davidtessier** [comment]
<img width="366" alt="3OvDQy5mqz" src="https://user-images.githubusercontent.com/1824441/229521529-96130379-081e-4ed2-b101-3fbf8cc730d2.png">

**Comment by nmuise-barclay** [comment]
I'm using DBeaver 23.0.3, also experiencing this issue. However, disabling "Show statistics for multiple queries with results" as @davidtessier suggested had no effect, even after restarting DBeaver - I still get unwanted Statistics tabs.

However, I only get Statistics tabs when I execute a statement or group of statements that includes some transaction operation (i.e. `BEGIN;`, `ROLLBACK;`, or `COMMIT;`). Moreover, I don't need to execute multiple queries for the Statistics tab to be generated - whether I execute one query or many queries, a Statistics tab will be generated if any of the executed statements was a transaction operation.

That is to say, all of the following will generate a Statistics tab, in addition to whatever output tabs the query (or queries) would normally generate (if any), and that Statistics tab will always take precedence over the other output tabs, no matter where in the executed statement(s) the transaction operation was:

```sql
BEGIN;
```
```sql
BEGIN;
SELECT 1;
```
```sql
SELECT 1;
SELECT 2;
ROLLBACK;
```

**Comment by koutelis** [comment]
I 2nd @nmuise-barclay ,
however I always get statistics transactional query or not.
I run my queries as scripts in the SQL console

**Comment by Theanderblast** [comment]
so freaking annoying

**Comment by manguicho** [comment]
Can it be disabled? it's insane

**Comment by thiagobraga** [comment]
Using 23.1.1.202306251800 and it's still happening. It's very annoying.

**Comment by wesleyaip** [comment]
Same problem here... Using 23.1.3.202307231901.

**Comment by viktorpromofarma** [comment]
Same problem ...... 31/07/2023

**Comment by lsergioa** [comment]
Same problem 02/08/23 ver 23.1.3 (24.07.2023)

**Comment by paul-eeoc** [comment]
It's back. The statistics tab would periodically spontaneously load after I run a query.  Version 23.1.4.202308061552 (August 7, 2023).

**Comment by coleman-rik** [comment]
It seems like there are those who don't want the statistics tab, and others, like myself, who always want the statistics tab.
The proposed solution seems to be to remove the statistics tab and then give users the option to only show it when multiple queries are run.
Unfortunately, it seems that even that attempt doesn't work correctly.

Personally, I think there a couple of avenues that can be explored.
1. switch the option from the current "Show statistics for multiple queries with results" to something like; 
    - never show statistics panel
    - always show statistics panel
    - only show statistics panel when running multiple queries
2. don't force the statistics panel to have focus.

The bigger pain point I am reading here doesn't appear to be the statistics panel, but the fact the dBeaver forces it to have focus whenever a script is run.  This goes along with another bug that is the output panel randomly disappearing and reappearing, often forcing a Ctrl+Shift+O to display it.

Users should have more options.  In this case that being which panel to receive focus when a query finishes running.
- statistics panel
- output panel
- 1st results panel

Ideally there should be an order of operations, in the event that any particular script doesn't generate an output or any results.
Something like:

Query completion panel order:
( ) - 1st results panel
( ) - output panel
( ) - statistics panel

and the user could specify the order they want them in with the first applicable panel having focus.

ex:

Query completion panel order:
( 2 ) - 1st results panel
( 1 ) - output panel
( 3 ) - statistics panel

with the understanding that if a particular query isn't applicable, either for example because there aren't any results, or because the user has indicated that they don't want to ever see statistics, that it would fall through to the next highest numbered choice.

Of course, it should go without saying that any such options will need to work consistently and reliably.

I hope that helps,

**Comment by paul-eeoc** [comment]
@coleman-rik Here is the thing:
I am running only a single query like this:
_SELECT * FROM shared_code;_

And I get no statistics tab.

However, if I have a comment after it like this:
_SELECT * FROM shared_code;
--order by 1_

Then I get the statistics tab.  This is a bug.

**Comment by btanner2** [comment]
It would be good to reopen this issue here since the bug came back with version 3.1.1, as you can read here:

#20416

**Comment by jaypan13** [comment]
This is definitely annoying. As the version is controlled by my organization, on mac with Version - 23.2.0.202309031556, it still shows statistics window unnecessary when looking to get results of the query and it switches to that. Please reopen this bug!
There is another hidden bug if you are running mysql queries on mac os. Not sure if that happens on windows and with any other database engines.
You put your simple query and on the next line put #. You cannot edit inline!
E.g. 

```
Select * from table1;
#this is test
```

**Comment by pfc2001** [comment]
I'm using Version 23.2.0.202309041200 and agree that this is very annoying. I have found that if you're running a single sql statement and you leave the semicolon off you can have a comment after the statement and the statistics tab doesn't display.

![image](https://github.com/dbeaver/dbeaver/assets/145573655/50dc1e37-3f94-48e7-9c4d-ae83ed2a3d36)

With the semicolon in place, clicking the "Execute SQL Query" icon 
![image](https://github.com/dbeaver/dbeaver/assets/145573655/523a24e7-5b6d-46c6-8c63-d0b3aeceb7d2)
(not the "Execute SQL Script" icon 
![image](https://github.com/dbeaver/dbeaver/assets/145573655/13c77f74-b8ec-4ebd-8810-bd041e08da61)
), also doesn't display the statistics tab.

While not a fix for the bug, these workarounds help when iterating through the development of a query.

**Comment by manguicho** [comment]
It's very insane dude

**Comment by xavipolo** [comment]
Same problem when doing an "Execute > Export from Query" to run a script and export the result. The statistics are generated and appended to the beginning of the result, which makes pasting the result into an Excel file a pain, as it kills any attempt to use the Import Wizard, which expects to receive the data in tabular form only.

**Comment by azzztec** [comment]
Still the same problem. I press **Execute SQL Query** button and instead of result i see statistic

<img width="920" height="523" alt="Image" src="https://github.com/user-attachments/assets/50069b7a-4d36-4016-b12f-7bb78db2d637" />

**Comment by E1izabeth** [comment]
@azzztec it looks like you executed SQL comment

**Comment by azzztec** [comment]
> [@azzztec](https://github.com/azzztec) it looks like you executed SQL comment

))) how it works i cannot understand, why comment was executed. But it doesnt metter because in some cases i have the same problem even when after all comments removed

**Comment by E1izabeth** [comment]
https://github.com/dbeaver/dbeaver/wiki/SQL-Execution
