### ISSUE TITLE
Saving SQL editor remove active connection

### ISSUE THREAD

**Issue by jcurlier** [dbeaver/dbeaver#7892]
System information:
- Operating system (distribution) and version: Mac
- DBeaver version:  6.3.4.202002011957

#### Describe the problem you're observing:

When saving the SQL editor (Command > S), the active connection for the editor is removed - I need to reset it every time I save the SQL file.

#### Steps to reproduce, if exist:

1) Create a new SQL editor
2) Create a query in the editor
3) Connect to a database
4) Set the connection as the active connection for the editor
5) Execute the query
6) Save the editor (Command > Save)

The active connection is removed from the editor.

**Comment by uslss** [comment]
@jcurlier ,
unfortunately, we cannot reproduce an issue. Could you add a video?

**Comment by jcurlier** [comment]
Sorry - I found a workaround: save the SQL file in the editor under a different name and the issue went away. It it happens again I will for sure make a video.

**Comment by uslss** [comment]
seems that the issue is resolved for now. Ticket will be closed.
If it will reproduce once again, feel free to reopen the ticket and add additional info :)

**Comment by tkorach** [comment]
It happens to me as well. Once an editor is saved, the editor is detached. 

Steps to reproduce:

1. Open and SQL editor. 
1. Choose a connection in the "Active datasource" toolbar. 
1. Type some text. 
1. Save the editor (using either Ctrl+s or "File-> save" menu. 

Result: the "Active datasource" indicator becomes "N/A".

It started about 3 months ago. Changing the connection settings in "SQL Editor" did not help.

**Comment by gchiaia** [comment]
I had the same problem and figured out what to do (at least for DBeaver in Eclipse).

Before I had my connection opened under a different Eclipse project (DBeaver), while using this connection in a different project (Let's say ProjectX). Just copy the DB connection from the default location (DBeaver) and paste it in the DB connections of your specific project (ProjectX). Or change the active project to ProjectX.
Then that attach your script to this latter connection (in your project).

DBeaver writes the connection links in a .dbeaver directory under your active project, but get confused when two different projects are involved.

This has fixed this problem for me

**Comment by pys-arhs** [comment]
I noticed the same issue with DBeaver 7.0.2.202004051509 on Windows 10.

**Comment by tkorach** [comment]
@gchiaia I tried and it did not solve the problem. 
DBeaver 7.0.0.202003021717

**Comment by liumingkun** [comment]
I am running Version 7.1.4.202008021649 on Win10. Having the same problem

**Comment by liumingkun** [comment]
Found one workaround/fix - 
1) set up a project; 
2) create connections in the project; 
3) create the query file in the project; 
4) open the query file in SQL Editor & add the notation of connection on the 1st line, such as -
-- CONNECTION: name=MY_DB_CONNECTION

Now the connection won't be dropped when saving the query file.

**Comment by arobinsongit** [comment]
Tried the -- CONNECTION: name=MY_DB_CONNECTION trick on Version 21.3.5.202202200327 Community edition and still get an active connection drop.

**Comment by adeel-raza-azeemi** [comment]
Same issue here on
Ubuntu 20.04.4 LTS (64 bit)

As soon as I save the SQL script file active connection got lost. (Or to N/A)

@liumingkun solution didn't worked for me . I put the first line in my script file to 
-- CONNECTION: name=util

    i.e. util being my connection name

but it also didn't worked.

**Comment by daliborp76** [comment]
Same here
Win11, DBeaver 22.2.1.202209251341
Any code buffer SAVE action (CTRL+S, save from menu) resets current connection (disconnects) thus invalidates current session

**Comment by open2bonobo** [comment]
The same issue Version 24.3.4.202502021521 . When i press ctrl+s in sql script it 100% always disconnet me from SQLight
This issue was alway on my PC.

![Image](https://github.com/user-attachments/assets/f06b27b5-ffef-4ea8-b9ff-68c7e60899bd)
**CTRL+S**

![Image](https://github.com/user-attachments/assets/1443d21d-9f02-40fb-95e7-a7096a28e06f)
