### ISSUE TITLE
Exporting table to another table does not keep upper case characters or quotes in names

### ISSUE THREAD

**Issue by tdauth** [dbeaver/dbeaver#7911]
#### System information: 
- Operating system (distribution) and version: Linux ubuntu 5.3.0-28-generic #30~18.04.1-Ubuntu
- DBeaver version:  Version 6.3.4.202002011957
- Additional extensions

#### Connection specification:
- Database name and version: PostgreSQL 10 and 12
- Driver name: org.postgresql.Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)?  no

#### Describe the problem you're observing:

When I click at my table and at "Export data" and target "Database" and I export the table from a PostgreSQL 10 database to my local PostgreSQL 12 database it does not keep upper cases or quotes in the table's name or column names.
For example if my original table's name is "Data" it will be data.
If my column's name is "fileName" it will be filename.
This is annoying since I want to test scripts at the copy

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed. Target table name and column names will be in quoted form for case-sensitive source names.

**Comment by uslss** [comment]
verified

**Comment by JimAlexanderDDI** [comment]
Data Transfer Export to Database; Version 7.0.2 (and I'm thinking since 7.0.0) now takes an AS400 uppercase Source Column and maps to a PostgreSQL quoted uppercase Target Column, yet PostgreSQL requires column names to be lowercase. DBeaver version 6.3.3 and prior at least 2 years mapped the PostgreSQL Target Column to lowercase. Is this a bug or by design?

**Comment by bilhega** [comment]
Same @JimAlexanderDDI issue in a Data Transfer from a Firebird 3.0.4 to PostgreSQL 12.1. The table names gets in lowercase, but column names get quoted.

Should this operation look at connections configuration ( or global configuration ), in metadata section, "Use case-sensitive names in DDL statements" ? Mine is uncheched on both connections and on global config.

Version 7.0.4

**Comment by leonpierre** [comment]
This is still valid with DBeaver v21.3.5 and Postgresql 13:

when exporting tables from a Postgresql DB to my local DB the table / column names doesn't keep the Uppercase
characters.

So it's not fixed in the latest DBeaver version, or did I miss something?

Thx

**Comment by fimperioli-b2w** [comment]
Still here, also with the latest version

**Comment by vgrimaldi848** [comment]
Not sure if this is a bug or not but you should try to edit the connection definition and:
Metadata - > Unchecjk default option -> Check "Use case-sensitive names in DDL statements".

Worked for me.

**Comment by joshasbuilt** [comment]
Not sure if this is a bug or not but you should try to edit the connection definition and:
Metadata - > Unchecjk default option -> Check "Use case-sensitive names in DDL statements".

Worked for me.  AND RENAME (OR REMOVE) THE PREVIOUS FAILED ATTEMPTS.

**Comment by JimAlexanderDDI** [comment]
Thanks! Bug has been fixed.

**Comment by zwcloud** [comment]
> Not sure if this is a bug or not but you should try to edit the connection definition and: Metadata - > Unchecjk default option -> Check "Use case-sensitive names in DDL statements".
> 
> Worked for me.

That should be made enabled by default. @serge-rider
Also this option doesn't preserve table name case.
