### ISSUE TITLE
Error resolving driver dependencies mssql-jdbc_auth

### ISSUE THREAD

**Issue by P4Ks** [dbeaver/dbeaver#8251]
Hello, after 7.0.1 update ( from 6.* release) mssql auth library is missing and it was not possible to connect to mssql db anymore .

Error:
`Error resolving dependencies
  Maven artifact 'maven:/com.microsoft.sqlserver:mssql-jdbc_auth:RELEASE' not found
  Maven artifact 'maven:/com.microsoft.sqlserver:mssql-jdbc_auth:RELEASE' not found`

This issue probably it's linked to https://github.com/dbeaver/dbeaver/issues/8054 

under %appdata%\DBeaverData\drivers\drivers\mssql\auth\x64  I've an old sqljdbc_auth.dll that worked well before 7.* release.

I've manually downloaded the new dll: https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc_auth/8.2.1.x64 and added it to driver to libraries files and **with this workaround it work**s. but everytime that I try to connect to a mssql db I get the error of missing dependencies.

I'm using home dsl , no proxy authentication , no VPN enabled.
OS: windows 7
Dbeaver version: 7.0.1

**Comment by serge-rider** [comment]
Try to reset driver settings.
From connection settings dialog click Edit Driver Settings -> Reset to Defaults (at the bottom). 
Then dbeaver should ask for driver jars/dlls re-download.

**Comment by P4Ks** [comment]
I've reset to default mssql driver settings and re-downloaded latest driver version, this solved the problem of auth library dependency, thanks!

access to mssql database with SQL server authentication works well.

access to mssql database with windows authentication give me this error:

`no mssql-jdbc_auth-8.2.1.x64 in java.library.path: [C:\Program Files\DBeaver, C:\WINDOWS\Sun\Java\bin, C:\WINDOWS\system32, C:\WINDOWS, C:/Program Files/DBeaver/jre/bin/server, C:/Program Files/DBeaver/jre/bin, C:\WINDOWS\system32, C:\WINDOWS, C:\WINDOWS\System32\Wbem, C:\WINDOWS\System32\WindowsPowerShell\v1.0\, C:\Program Files (x86)\QuickTime\QTSystem\, C:\Program Files (x86)\IBM\Client Access\Emulator, C:\Program Files (x86)\IBM\Client Access\Shared, C:\Program Files (x86)\IBM\Client Access\, c:\Program Files\Microsoft Data Protection Manager\DPM\bin\VDDK\bin\, C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\, C:\Program Files\DBeaver, ., .]`

this problem was raised because libraries versions where a little bit different 
mssql-jdbc : 8.2.1
mssql-jdbc_auth: 8.2.0

[As I learned from your post](https://github.com/dbeaver/dbeaver/issues/8054#issuecomment-593450076)  I've forced auth library to 8.2.1 version, because libraries must have the same versions, and this fixed the problem. I'm reporting this because some people may face the same situation if they don't know about new required version dependency, because dbeaver allow you to have different library versions.

Thanks @serge-rider !

**Comment by alexlaedi** [comment]
I can confirm that the issue still prevails after resetting when windows authentication is used to connect to MS SQL and different library versions exist. I get the same error as P4Ks.

**Comment by uslss** [comment]
Reset to default works incorrectly
![2020-03-24_15h45_22](https://user-images.githubusercontent.com/31996417/77427530-a2894700-6de7-11ea-93bc-ba36fd94b471.gif)

**Comment by flocoolb** [comment]
Hello,
I have the same issue. I am not able to connect using Windows Authentication, but using 'SQL server authentication' it works well.
I tried to reset to default and download again, but it is still the same thing.

I did not understand how I can manage this issue. Maybe there will be a fix soon anyway?

Thanks for your help

**Comment by uslss** [comment]
@flocoolb just choose the same version manually for both files when you download drivers
![image](https://user-images.githubusercontent.com/31996417/77455782-5c45df00-6e0b-11ea-88e8-207e48d8e142.png)

**Comment by flocoolb** [comment]
Thank you very much @uslss 
I am not used to change things like those. I understood with your last screenshot. Thanks! 

By the way, there is the 8.2.2 since yesterday.
Have a good day

**Comment by serge-rider** [comment]
"Reset to default" fixed

**Comment by yiting-wang-dl** [comment]
I have the same error "no mssql-jdbc_auth-8.2.0.x64 in java library path: " .
I use MacOS Catalina. Both mssql-jdbc and mssql-jdbc_auth are version 8.2.0. 
<img width="689" alt="image" src="https://user-images.githubusercontent.com/37285002/78471630-948ccd80-76e7-11ea-8bad-3445548d9775.png">
However, the "download/update" window only have mssql-jdbc, no JDBC_auth. 
<img width="692" alt="image" src="https://user-images.githubusercontent.com/37285002/78471677-efbec000-76e7-11ea-9bbc-0926ffcbeda1.png">
I also manually downloaded the auth-8.2.0.x64.dll and put it in the maven-central/com.microsoft.sqlserver folder. This didn't work either.

**Comment by uslss** [comment]
verified.
Fixed in scope of 7.0.2 release.
Could be tested in EA version (https://dbeaver.io/files/ea/)

**Comment by TrongNguyenVann** [comment]
I have fixed this issue by following step:
1. Download Microsoft JDBC Driver for SQL Server from https://docs.microsoft.com/en-us/sql/connect/jdbc/download-microsoft-jdbc-driver-for-sql-server?view=sql-server-ver15
2. Extract it and copy extracted folder to C:\Program Files\DBeaver\plugins
3. Open your connection to DB, click on Edit Driver delete old jar file and specify path to parent folder of downloaded jar s file

Hope that help!

**Comment by yezhengli-Mr9** [comment]
> I have fixed this issue by following step:
> 
> 1. Download Microsoft JDBC Driver for SQL Server from https://docs.microsoft.com/en-us/sql/connect/jdbc/download-microsoft-jdbc-driver-for-sql-server?view=sql-server-ver15
> 2. Extract it and copy extracted folder to C:\Program Files\DBeaver\plugins
> 3. Open your connection to DB, click on Edit Driver delete old jar file and specify path to parent folder of downloaded jar s file
> 
> Hope that help!

**MacOS Monterey**
**DBeaver 22.3.1**
```java
no mssql-jdbc_auth-9.2.0.x64 in java.library.path: 

/Users/***/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
```
Can download `mssql-jdbc_auth-9.2.0.x64.dll`, `mssql-jdbc-9.2.0.jre8.jar`, `mssql-jdbc-9.2.0.jre11.jar`, `mssql-jdbc-9.2.0.jre15.jar` from [here](https://learn.microsoft.com/en-us/sql/connect/jdbc/release-notes-for-the-jdbc-driver?view=sql-server-ver16) and put it in both `/Users/***/Library/Java/Extensions` and `/Library/Java/Extensions` but still does not work.
