### ISSUE TITLE
Refresh cached metadata/navigator tree after manual DDL processing

### ISSUE THREAD

**Issue by dbza** [dbeaver/dbeaver#859]
Steps to reproduce:
- Create a new table with create table and commit.
- do a "select \* " fromthe new table
- In the results GUI, try to add new rows using the "+" button, enter values for all cells and click the "apply data changes"

Error messgae;

> !ENTRY org.jkiss.dbeaver.model 4 0 2016-10-18 15:54:28.882
> !MESSAGE org.jkiss.dbeaver.model.exec.DBCException: Internal error: can't obtain entity identifier
> !SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2016-10-18 15:54:28.882
> !MESSAGE Internal error: can't obtain entity identifier
> !STACK 0
> org.jkiss.dbeaver.model.exec.DBCException: Internal error: can't obtain entity identifier
>   at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister.getDefaultRowIdentifier(ResultSetPersister.java:335)
>   at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister.prepareDeleteStatements(ResultSetPersister.java:169)
>   at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister.applyChanges(ResultSetPersister.java:125)
>   at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.applyChanges(ResultSetViewer.java:2241)
>   at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.applyChanges(ResultSetViewer.java:2229)
>   at org.jkiss.dbeaver.ui.controls.resultset.ResultSetCommandHandler.execute(ResultSetCommandHandler.java:165)
>   at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
>   at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
>   at sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:498)
>   at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
>   at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:252)
>   at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:234)
>   at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
>   at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
>   at org.eclipse.core.commands.Command.executeWithChecks(Command.java:493)
>   at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:486)
>   at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
>   at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:343)
>   at org.eclipse.ui.menus.CommandContributionItem.handleWidgetSelection(CommandContributionItem.java:830)
>   at org.eclipse.ui.menus.CommandContributionItem.access$21(CommandContributionItem.java:816)
>   at org.eclipse.ui.menus.CommandContributionItem$5.handleEvent(CommandContributionItem.java:806)
>   at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
>   at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
>   at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
>   at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)
>   at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
>   at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
>   at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
>   at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
>   at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
>   at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
>   at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
>   at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
>   at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
>   at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:193)
>   at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
>   at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
>   at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
>   at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
>   at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:498)
>   at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
>   at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
>   at org.eclipse.equinox.launcher.Main.run(Main.java:1515)

**Comment by serge-rider** [comment]
Can't reproduce. From error log I see that error happens during row delete operation. Maybe you made a few other data modifications besides new rows addition?
Anyhow I can't reproduce that even with if I do rows copy/modify/delete.
BTW does your new table has a primary/unique key?

**Comment by Sargul** [comment]
@dbza try this
1. create table as select * from ....
2. commit
3. click on the active connection in the hierarchy on the left
4. hit F5 key  to refresh the meta data
5. now do the select
6. click + and apply and safe

I'm pretty sure this should work now.

I could definitely reproduce the issue with the DB2 and maria/mysql db plugin:

1. create table dummy (col1 integer);
2. select * from dummy;
3. hit + in the output 
4. apply 
5. Error

@serge-rider is there a CREATE Object detection in the SQL parser? We should do a refresh of the object caches when an new object is created. A safe way would be to refresh metadata as soon as a create statement is detected. This could severely impact performance as a refresh may take a while.

**Comment by serge-rider** [comment]
Still can't reproduce that error. Works without any error in MySQL.

Agreed about refreshing metadata after DDL execution. Although this should be a smart refresh..

**Comment by dbza** [comment]
It seems the refreshing solves the issue. But without that I still get the error.

**Comment by dbza** [comment]
If I do a "alt+x" to run it works. I was executing single statements earlier. While running as a script, It shows a brief message window I think while re-reading metadata and it seem to solve the issue. not sure if  something needs to be done for individual statements run via ctrl+enter.

![image](https://cloud.githubusercontent.com/assets/419093/19709300/4242d3ae-9ada-11e6-89be-ceb99a204c36.png)

**Comment by serge-rider** [comment]
That was tricky.

I think you have disabled all confirmation dialogs.
You have modified resultset. When you execute another query DBeaver asks you do you want to save changes (you can disable this confirmation with "always yes").
In that case DBeaver will try to save changes. 
If your table doesn't have a unique key then DBeaver will ask for one. You can also disable this confirmation ("Always use all columns as key").
As you didn't refresh metadata Deaver can't find information about just created table and can't define a key for it.
And fails with that error.

Workaround: just cancel all changes (Cancel button in the toolbar) before new query execution.

**Comment by braiam** [comment]
@serge-rider I've managed to reproduce this behavior without dismissing any confirmation dialog. Both Save and Script fails with "can't get single entity metadata, insert is not possible". I've also refreshed the metadata in the sidebar without changes. Should I open another bug? 10.3.10-MariaDB-log.

**Comment by uslss** [comment]
can't reproduce it against the recent version.
The ticket will be closed. if the issue is still actual for you - feel free to reopen the ticket
