### ISSUE TITLE
postgreSQL driver: allow connection through a PG service name

### ISSUE THREAD

**Issue by suz-estella** [dbeaver/dbeaver#8756]
Hi there!

I am looking to share a project folder over a network with multiple users. We are seeking to connect to a single database, with a number of pre-set table and view bookmarks. Each user has their own username and password, which means we cannot currently share the same postgreSQL "connection."

Would you consider adding support for connection to a postgreSQL database via a PG service name? This would allow user to connect to the same database using different credentials. All users would have the "PGSERVICEFILE" and "PGPASSFILE" environmental variables set.

See postgreSQL documentation here: [https://www.postgresql.org/docs/current/libpq-pgservice.html](https://www.postgresql.org/docs/current/libpq-pgservice.html)

Please advice if I have missed some way to share bookmarked database objects from different connections to the same database.

Thank you!

**Comment by suz-estella** [comment]
I think I have solved my own question by using the "PGUSER" environmental variable reference for username while connecting with the PgPass method. May re-open if there is some other issue sharing the project folder.

Thank you anyway!

**Comment by mpasquini** [comment]
I vote, 
Not all knows about this PostgreSQL feature, the PGSERVICEFILE, that in conjunction with a personal PGPASSFILE is total win. 
In many cases you need to connect to tens or hundred of databases and also you have to share with other developers. 
..As described in first comment: https://github.com/dbeaver/dbeaver/issues/8756#issue-622011159

So that you can say to your colleagues 'set "service=dev-maindb" ' and the problem is solved !!!

Having this new feature in dbeaver will make this software more precious.

For now I will NOT use dbeaver cause I'm lazy to create my 92 connections.....by hand, 1 by 1

**Comment by ikzelf** [comment]
an other reason for wanting to use the PGSERVICE file is that it allows to specify a hosts list for a service and a target_session_attrs. If I am reading this correctly, the driver supports this url config since pgjdbc 42.3
Using dbeaver 22.3.2 I get "Unable to parse URL jdbc:postgresql://?service=xxx" when trying to use a service that is listed in the %PGSERVICEFILE%
Digging a bit deeper, I see that dbeaver passes the url to the driver parser. Too bad that the driver parser uses different rules and names for the parameters compared to the libpq implementation.

**Comment by vlcinsky** [comment]
@suz-estella could you consider reopening this feature request?

You have closed it as you have found a working work around for your needs but the request for support of `~/.pg_service.conf` is not resolved and as seen from other reaction, it would be really appreciated.
