### ISSUE TITLE
Unable to save postgres custom type array

### ISSUE THREAD

**Issue by rodriguise** [dbeaver/dbeaver#8845]
#### System information: 
- Windows 10 Pro
- Version 7.0.5.202005171753

#### Connection specification:
- Postgres 12.2
- PostgreSQL JDBC Driver 42.2.5
- No tunnels or proxies

#### Describe the problem you're observing:
Unable to save array of custom type. The error provided is:
```
Error synchronizing data with database

Reason:
Error creating struct
```

```
Error creating struct
  Unable to find server array type for provided name <type_name>.
```

#### Steps to reproduce, if exist:
```sql
CREATE SCHEMA IF NOT EXISTS  "cc";

CREATE TYPE cc.my_type as ENUM ('foo', 'bar');

CREATE TABLE IF NOT EXISTS cc.my_table(
 ID SERIAL PRIMARY KEY,
 props cc.my_type[]
);
```

In the UI add a new row and populate the `props` with a value. Click `Save`.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Fixed (by using FQ type name)

**Comment by uslss** [comment]
verified

**Comment by mittalyashu** [comment]
<img width="642" alt="Screenshot 2020-08-04 at 10 21 02 AM" src="https://user-images.githubusercontent.com/29014463/89254189-355eab80-d63c-11ea-8d13-c1ae5dad038a.png">

@uslss In the recent release `v7.1.4`, I am getting the same/similar error.

In the previous release `v7.1.3` or `v7.1.2` _(don't remember the exact version number)_, I didn't get such issue.

**Comment by sridharjsharma** [comment]
![image](https://user-images.githubusercontent.com/34868101/93854812-08418780-fcd4-11ea-8067-132987699f47.png)

This Issue Still Exists?
I'm on 7.2.1 win10 m/c

**Comment by shawnngtq** [comment]
@uslss 

I am currently using dbeaver 7.2.2 on my ubuntu OS and notice the same problem for my PostgreSQL database.

For `_varchar` and `_numeric` datatype

**Comment by JVKdouk** [comment]
This issue is still present on DBeaver. For some reason, it cannot update Array columns of custom type!

**Comment by p91paul** [comment]
@JVKdouk I advise you to open a new issue, this one's closed
