### ISSUE TITLE
Generate SQL utility missing

### ISSUE THREAD

**Issue by rpalloni** [dbeaver/dbeaver#9060]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 7.1.1

#### Connection specification:
- Database name and version: Oracle 
- Driver name: JDBC

#### Describe the problem you're observing: 
When right clicking a record the menu does not display the Generate sql utility https://dbeaver.com/docs/wiki/SQL-Generation/

#### Steps to reproduce, if exist: 
right click a record

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Can't reproduce

**Comment by serge-rider** [comment]
Well, this is even worse. Table editor isn't working for Oracle.

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified

**Comment by aderchox** [comment]
Weird, but I had the same issue and even when I refresh in the table("data" tab), the lock icon on the column name is not gone, then I go to the table's properties("properties" tab) and refresh in there, now the column name appears, and when I go back to the table, the lock icon is gone and the problem is fixed!

**Comment by pakhuta** [comment]
@aderchox , thanks for the life hack!

**Comment by lovelock** [comment]
Still have the same issue.

Version 7.2.3.202010181902

<img width="856" alt="image" src="https://user-images.githubusercontent.com/2208731/99049368-b6c9c080-25d1-11eb-943a-33fce3f3d549.png">

**Comment by lovelock** [comment]
> Still have the same issue.
> 
> Version 7.2.3.202010181902
> 
> <img alt="image" width="856" src="https://user-images.githubusercontent.com/2208731/99049368-b6c9c080-25d1-11eb-943a-33fce3f3d549.png">

And datagrip has the same issue.
