### ISSUE TITLE
Editing column data in UI does not work when primary key is uuid

### ISSUE THREAD

**Issue by nheilbuth** [dbeaver/dbeaver#9964]
#### System information: 
- Operating system (distribution) and version: **Windows 10**
- DBeaver version: **7.2.2.202010041557**

#### Connection specification:
- Database name and verison: **Postgres (tested on 9.6 and 11)**
- Driver name: **PostgreSQL JDBC Driver**
- Do you use tunnels or proxies (SSH, SOCKS, etc): **No**

#### Describe the problem you're observing:
When editing the value of a cell, pressing "Save" will give the error `Object parameter [4e3f75d2-3375-4040-9c02-3a8c15a8be87] binding not supported` where 4e3f75d2-3375-4040-9c02-3a8c15a8be87 is the value of the primary key column.
The primary key column is of type uuid. The type of the edited cell it self does not seem to matter (tested with text, int and jsonb).
Doing the same on a table with primary key of type int, works fine.

#### Steps to reproduce, if exist:
```
CREATE TABLE test (
  id uuid,
  name text,
  PRIMARY KEY (id)
);
```

```
INSERT INTO test 
  VALUES 
    ('72644fac-9e7b-4da3-b801-ba80c1bb4fd5', 'test 1'), 
    ('6b24f99a-4c58-4bac-92c3-5a756281d431', 'test 2');
```

```
SELECT * FROM test;
```

Mark one of the `name` cells and press shift+enter to open the editor.
![image](https://user-images.githubusercontent.com/1744634/95048802-cb6c8c00-06e8-11eb-9de7-3b7226f31a25.png)

Change the value and press "Save"

Press "Save" in the bottom left (or ctrl+s).

Gives this error:
![image](https://user-images.githubusercontent.com/1744634/95048908-fb1b9400-06e8-11eb-9917-aa1feaa131d5.png)

If I do the same with a table that has an int primary key column (instead of a uuid), it works just fine.

#### Include any warning/errors/backtraces from the logs
!ENTRY org.jkiss.dbeaver.model 4 0 2020-10-05 08:58:29.382
!MESSAGE Object parameter [6b24f99a-4c58-4bac-92c3-5a756281d431] binding not supported
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2020-10-05 08:58:29.382
!MESSAGE Object parameter [6b24f99a-4c58-4bac-92c3-5a756281d431] binding not supported
!STACK 0
org.jkiss.dbeaver.model.exec.DBCException: Object parameter [6b24f99a-4c58-4bac-92c3-5a756281d431] binding not supported
	at org.jkiss.dbeaver.model.impl.data.DefaultValueHandler.bindValueObject(DefaultValueHandler.java:60)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable$2.bindStatement(JDBCTable.java:466)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.processBatch(ExecuteBatchImpl.java:156)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.execute(ExecuteBatchImpl.java:77)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.executeStatements(ResultSetPersister.java:804)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.lambda$1(ResultSetPersister.java:690)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.executeStatements(ResultSetPersister.java:689)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.run(ResultSetPersister.java:627)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by amfine-soft-drault** [comment]
Hi 
same issue here (linux + java 11 + dbeaver Version 7.2.2.202010041557)
i display some data, try to delete the row and save : i get the same error 
i display some data, try to edit some cell and save :  i get the same error 
downgraded to 7.2.1 and this works just fine

**Comment by william00179** [comment]
+1 for this issue. Rolling back to 7.2.1.

**Comment by manuellp12** [comment]
Same issue, I updated dbeaver a few hours ago and same problem, please update the eclipse update site for the fix.

**Comment by Remi-C** [comment]
Same issue for several of my students :-/
Does not affects the pro version, only the CE?

**Comment by jbrawnjr** [comment]
Also experiencing this issue. It must have started in a recent release, because I have been using DBeaver for several months and have been able to update tables with uuid primary keys successfully until just recently.

**Comment by Remi-C** [comment]
If that helps, having composite types in primary keys is also creating a mess

**Comment by jbrawnjr** [comment]
I just uninstalled 7.2.2 and installed 7.2.1 and I can confirm that the issue is not present in 7.2.1.

**Comment by josh-tracey** [comment]
+1 same issue

**Comment by felipeamsv** [comment]
Same issue here, while editing/deleting/creating rows using the Data Editor in tables that use UUID as their primary key OR with composite primary keys. No issues with a written script.

Adding to this, it is also not possible to generate the INSERT/UPDATE/DELETE statement from the Data Editor after editing the data as desired, as it shows the same "binding not supported" error.

Rolling back to 7.2.1 until this is resolved.

**Comment by respectTheCode** [comment]
Same problem here. Rolled back to 7.2.1 and everything works.

https://dbeaver.io/files/7.2.1/

**Comment by nikitades** [comment]
+1 Also rolled back to 7.2.1.

**Comment by EdwardHiscoke** [comment]
+1 A quick roll back and everything works fine!

**Comment by MatheusRamos90** [comment]
Same problem here :/
Also rolled back to 7.2.1

**Comment by pedrogodoy** [comment]
Same problem here. Version 7.2.2

**Comment by bradrogers-nw** [comment]
+1 broken in 7.2.2, fine in 7.2.1.

**Comment by mortifia** [comment]
+1 broken in 7.2.2

**Comment by lachlan-oneflick** [comment]
Same issue, broken in 7.2.2 for me.

**Comment by asankul** [comment]
+1 broken

**Comment by christianvershkov** [comment]
+1 broken in 7.2.2

**Comment by rafaelrpinto** [comment]
Folks, please click on the :+1: reaction button of the issue instead of creating a new +1 comment so people subscribed to this thread waiting for an actual update on the issue don't receive 10 useless emails a day until the next version is released.
Thank you.

**Comment by serge-rider** [comment]
Fixed.

We'll probably try to include the fix in the 7.2.3 version hotfix release.

**Comment by mortifia** [comment]
7.2.3 doesn't patch this bug

**Comment by chulanovskyi-bs** [comment]
@mortifia can't confirm. I've just upgraded to 7.2.3 and the cells editing (and saving) is working fine, no issues

**Comment by elbuguinho** [comment]
@chulanovskyi-bs I'm on Ubuntu and this bug persisted in this version for me.

**Comment by viktordd** [comment]
I still have the same issue on Version 7.2.3.202010181902
Same error if I try to generate a script instead of saving.
![image](https://user-images.githubusercontent.com/4382305/96494953-17552000-1215-11eb-8cb9-f0a7d79da358.png)

Also if you try to filter by a clipboard value (right click on uuid column -> Filter -> Clipboard -> ...) it shows the right statement, but it gets pasted without the quotes in the filter text box.
![image](https://user-images.githubusercontent.com/4382305/96494543-7e260980-1214-11eb-9af4-635b8c02b9c4.png)
![image](https://user-images.githubusercontent.com/4382305/96494675-aca3e480-1214-11eb-8aef-6ca47e1cacb0.png)
The filter by Cell Value gets pasted correctly.

**Comment by nheilbuth** [comment]
Looks like new hotfix version 7.2.3.202010191702 fixes the issue on Windows

**Comment by gertcominotto** [comment]
> Looks like new hotfix version 7.2.3.202010191702 fixes the issue on Windows

Just tried installing this version, but doesn't fix it for me.

**Comment by kseniiaguzeeva** [comment]
Seems the issue is still actual for Mac

**Comment by serge-rider** [comment]
Hotfix version 7.2.3 was published tonight.

@kseniiaguzeeva It doesn't depend on OS (or at least I can't figure out how it could depend on it).
We didn't update brew package (and other 3rd party packages), you will need to wait till 7.2.4 release if you use them.

**Comment by amfine-soft-drault** [comment]
downloaded 7.2.3 a few minutes ago and issue is fixed for me
thanks everyone

**Comment by KiSchulte** [comment]
Yes, I can confirm that Version 7.2.3.202010191702 fixed the issue.
I'm on Mac. 
@kseniiaguzeeva But I figured out that you have to take the package from the official Website. The package on GitHub Releases is still the one without the fix.

**Comment by serge-rider** [comment]
One more fixed applied.
Data type metadata read was broken in 7.2.2. When option "Show all databases" is off then primary database data types is read incorrectly.

New Early Access version with this fix is ready (https://dbeaver.io/files/ea). Please test.

**Comment by Libarch** [comment]
I am still having this issue with Version 7.2.3.202010191702 (Windows 10 64-bit). My primary key is varchar type. Works on 7.2.1

**Comment by kseniiaguzeeva** [comment]
verified. Tje fix will be available in 7.2.4 or you can download early access version (https://dbeaver.io/files/ea). Please test.

**Comment by Kazun3500** [comment]
error with postgresql and inet columns still present, checked on ea version/

![изображение](https://user-images.githubusercontent.com/13629272/96713308-0ccb8f80-13a9-11eb-9aff-10c8f54b4967.png)

**Comment by Libarch** [comment]
Fixed (for me) on Version 7.2.3.202010202034. Thanks!

**Comment by kseniiaguzeeva** [comment]
@Kazun3500 Thank you for the report. I can reproduce it for **inet** values (e.g. _PostgreSQL12 dvdrental."Xeniia"."10125"_)
  DBeaver	7.2.3.202010202034

**Comment by JekRock** [comment]
The issue is present in Version 7.2.3.202010191702 for the text datatype in PostgreSQL

**Comment by Libarch** [comment]
@JekRock 7.2.3.202010202034 works for me with varchar (on Windows)

**Comment by JekRock** [comment]
@Libarch but doesn't work for text on Windows

**Comment by ensiente** [comment]
![image](https://user-images.githubusercontent.com/37067911/97676191-12fcf280-1ab2-11eb-871e-55e9a95e62cb.png)


![image](https://user-images.githubusercontent.com/37067911/97676215-214b0e80-1ab2-11eb-8600-e5a80a8db144.png)
